mutation RubrikPolarisSDKRequest(
    $cloudVendor:                CloudVendor!,
    $cloudAccountId:             UUID,
    $customerTags:               [TagInput!]!,
    $excludedTags:               [String!],
    $shouldOverrideResourceTags: Boolean!,
) {
    result: setCustomerTags(input: {
        cloudVendor: $cloudVendor
        cloudAccountId: $cloudAccountId
        customerTags: {
            tagList: $customerTags
        }
        excludedTags: $excludedTags
        shouldOverrideResourceTags: $shouldOverrideResourceTags
    })
}
