query RubrikPolarisSDKRequest($after: String, $filter: [Filter!], $first: Int, $typeFilter: [HierarchyObjectTypeEnum!], $workloadHierarchy: WorkloadLevelHierarchy) {
    result: inventoryRoot {
        descendantConnection(after: $after, filter: $filter, first: $first, typeFilter: $typeFilter, workloadHierarchy: $workloadHierarchy) {
            nodes {
                name
                id
                objectType
                ... on AwsNativeAccount {
                    status
                    awsFeatures: enabledFeatures {
                        featureName
                        status
                        lastRefreshedAt
                    }
                }
                ... on AzureNativeSubscription {
                    azureSubscriptionStatus
                    azureSubscriptionNativeId
                    azureFeatures: enabledFeatures {
                        featureName
                        lastRefreshedAt
                        status
                    }
                }
                ... on AzureDevOpsProject {
                    orgId
                }
                ... on AzureDevOpsRepository {
                    orgId
                    projectId
                }
                ... on GithubRepository {
                    orgId
                }
                ... on AzureSqlManagedInstanceServer {
                    authType
                    azureResourceGroupDetails {
                        azureSubscriptionDetails {
                            id
                            name
                            accountConnectionId
                            tenantId
                            cloudType
                            status
                            regionSpecs {
                                region
                            }
                        }
                    }
                }
                ... on AzurePostgresFlexibleServer {
                    azureResourceGroupDetails {
                        azureSubscriptionDetails {
                            id
                            name
                            accountConnectionId
                            tenantId
                            cloudType
                            status
                            regionSpecs {
                                region
                            }
                        }
                    }
                }
            }
            count
            pageInfo {
                endCursor
                hasNextPage
            }
        }
    }
}

