// Code generated by queries_gen.go DO NOT EDIT.

// MIT License
//
// Copyright (c) 2021 Rubrik
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

package dspm

// allPolicyFilterTypes GraphQL query
var allPolicyFilterTypesQuery = `query SdkGolangAllPolicyFilterTypes($resourceType: PolicyResourceType!, $policyType: PolicyType!) {
    result: allPolicyFilterTypes(
        resourceType: $resourceType,
        policyType: $policyType
    )
}`

// allPolicyFilterValues GraphQL query
var allPolicyFilterValuesQuery = `query SdkGolangAllPolicyFilterValues($policyFilterType: FilterType!, $policyType: PolicyType!, $searchTerm: String) {
    result: allPolicyFilterValues(
        policyFilterType: $policyFilterType,
        policyType: $policyType,
        searchTerm: $searchTerm
    ) {
        possibleRelationships
        possibleValues {
            ... on FilterTreeValues {
                __typename
                filterValues {
                    value {
                        id
                        label
                    }
                    children {
                        value {
                            id
                            label
                        }
                    }
                }
            }
            ... on FilterValues {
                __typename
                filterValues {
                    id
                    label
                }
            }
            ... on FilterValuesWithProvider {
                __typename
                filterValuesWithProvider {
                    filterValue {
                        id
                        label
                    }
                    provider
                }
            }
        }
    }
}`

// allSecurityPolicies GraphQL query
var allSecurityPoliciesQuery = `query SdkGolangAllSecurityPolicies($policyTypes: [PolicyType!]!) {
    result: allSecurityPolicies(policyTypes: $policyTypes) {
        policy {
            policyId
            name
            description
            policyCategory
            policySeverity
            isEnabled
            isPredefined
            filter {
                ...FilterFields
            }
            thresholdFilter {
                ...FilterFields
            }
            createdAt
            updatedAt
        }
    }
}
fragment FilterFields on PolicyFilter {
    filterConfig {
        ... on FilterGroupConfig {
            __typename
            logicalOperator
            filtersList {
                filterConfig {
                    ... on FilterConfig {
                        __typename
                        type
                        values
                        relationship
                    }
                    ... on FilterGroupConfig {
                        __typename
                        logicalOperator
                        filtersList {
                            filterConfig {
                                ... on FilterConfig {
                                    __typename
                                    type
                                    values
                                    relationship
                                }
                            }
                        }
                    }
                }
            }
        }
        ... on FilterConfig {
            __typename
            type
            values
            relationship
        }
    }
}`

// createSecurityPolicy GraphQL query
var createSecurityPolicyQuery = `mutation SdkGolangCreateSecurityPolicy($input: CreateSecurityPolicyInput!) {
    result: createSecurityPolicy(input: $input) {
        policyId
    }
}`

// deleteSecurityPolicy GraphQL query
var deleteSecurityPolicyQuery = `mutation SdkGolangDeleteSecurityPolicy($policyId: UUID!, $policyType: PolicyType!) {
    result: deleteSecurityPolicy(policyId: $policyId, policyType: $policyType)
}`

// securityPolicy GraphQL query
var securityPolicyQuery = `query SdkGolangSecurityPolicy($policyId: UUID!, $policyType: PolicyType!) {
    result: securityPolicy(policyId: $policyId, policyType: $policyType) {
        policy {
            policyId
            policyType
            name
            description
            policyCategory
            policySeverity
            isEnabled
            isPredefined
            filter {
                ...FilterFields
            }
            thresholdFilter {
                ...FilterFields
            }
            createdAt
            updatedAt
        }
    }
}
fragment FilterFields on PolicyFilter {
    filterConfig {
        ... on FilterGroupConfig {
            __typename
            logicalOperator
            filtersList {
                filterConfig {
                    ... on FilterConfig {
                        __typename
                        type
                        values
                        relationship
                    }
                    ... on FilterGroupConfig {
                        __typename
                        logicalOperator
                        filtersList {
                            filterConfig {
                                ... on FilterConfig {
                                    __typename
                                    type
                                    values
                                    relationship
                                }
                            }
                        }
                    }
                }
            }
        }
        ... on FilterConfig {
            __typename
            type
            values
            relationship
        }
    }
}`

// updateSecurityPolicy GraphQL query
var updateSecurityPolicyQuery = `mutation SdkGolangUpdateSecurityPolicy($input: UpdateDSPMPolicyInput!) {
    result: updateSecurityPolicy(input: $input)
}`
