package cluster

// Timezone represents the valid cluster timezones.
type Timezone string

const (
	CLUSTER_TIMEZONE_UNSPECIFIED                    Timezone = "CLUSTER_TIMEZONE_UNSPECIFIED"
	CLUSTER_TIMEZONE_AFRICA_JOHANNESBURG            Timezone = "AFRICA_JOHANNESBURG"
	CLUSTER_TIMEZONE_AFRICA_LAGOS                   Timezone = "AFRICA_LAGOS"
	CLUSTER_TIMEZONE_AFRICA_NAIROBI                 Timezone = "AFRICA_NAIROBI"
	CLUSTER_TIMEZONE_AMERICA_ANCHORAGE              Timezone = "AMERICA_ANCHORAGE"
	CLUSTER_TIMEZONE_AMERICA_ARAGUAINA              Timezone = "AMERICA_ARAGUAINA"
	CLUSTER_TIMEZONE_AMERICA_ATIKOKAN               Timezone = "AMERICA_ATIKOKAN"
	CLUSTER_TIMEZONE_AMERICA_BARBADOS               Timezone = "AMERICA_BARBADOS"
	CLUSTER_TIMEZONE_AMERICA_BOGOTA                 Timezone = "AMERICA_BOGOTA"
	CLUSTER_TIMEZONE_AMERICA_CHICAGO                Timezone = "AMERICA_CHICAGO"
	CLUSTER_TIMEZONE_AMERICA_COSTA_RICA             Timezone = "AMERICA_COSTA_RICA"
	CLUSTER_TIMEZONE_AMERICA_DENVER                 Timezone = "AMERICA_DENVER"
	CLUSTER_TIMEZONE_AMERICA_LOS_ANGELES            Timezone = "AMERICA_LOS_ANGELES"
	CLUSTER_TIMEZONE_AMERICA_MEXICO_CITY            Timezone = "AMERICA_MEXICO_CITY"
	CLUSTER_TIMEZONE_AMERICA_NEW_YORK               Timezone = "AMERICA_NEW_YORK"
	CLUSTER_TIMEZONE_AMERICA_NORONHA                Timezone = "AMERICA_NORONHA"
	CLUSTER_TIMEZONE_AMERICA_PANAMA                 Timezone = "AMERICA_PANAMA"
	CLUSTER_TIMEZONE_AMERICA_PHOENIX                Timezone = "AMERICA_PHOENIX"
	CLUSTER_TIMEZONE_AMERICA_SANTIAGO               Timezone = "AMERICA_SANTIAGO"
	CLUSTER_TIMEZONE_AMERICA_ST_JOHNS               Timezone = "AMERICA_ST_JOHNS"
	CLUSTER_TIMEZONE_AMERICA_TORONTO                Timezone = "AMERICA_TORONTO"
	CLUSTER_TIMEZONE_AMERICA_VANCOUVER              Timezone = "AMERICA_VANCOUVER"
	CLUSTER_TIMEZONE_ASIA_BANGKOK                   Timezone = "ASIA_BANGKOK"
	CLUSTER_TIMEZONE_ASIA_DHAKA                     Timezone = "ASIA_DHAKA"
	CLUSTER_TIMEZONE_ASIA_DUBAI                     Timezone = "ASIA_DUBAI"
	CLUSTER_TIMEZONE_ASIA_HONG_KONG                 Timezone = "ASIA_HONG_KONG"
	CLUSTER_TIMEZONE_ASIA_KARACHI                   Timezone = "ASIA_KARACHI"
	CLUSTER_TIMEZONE_ASIA_KATHMANDU                 Timezone = "ASIA_KATHMANDU"
	CLUSTER_TIMEZONE_ASIA_KOLKATA                   Timezone = "ASIA_KOLKATA"
	CLUSTER_TIMEZONE_ASIA_MAGADAN                   Timezone = "ASIA_MAGADAN"
	CLUSTER_TIMEZONE_ASIA_SINGAPORE                 Timezone = "ASIA_SINGAPORE"
	CLUSTER_TIMEZONE_ASIA_TOKYO                     Timezone = "ASIA_TOKYO"
	CLUSTER_TIMEZONE_ATLANTIC_CAPE_VERDE            Timezone = "ATLANTIC_CAPE_VERDE"
	CLUSTER_TIMEZONE_AUSTRALIA_ADELAIDE             Timezone = "AUSTRALIA_ADELAIDE"
	CLUSTER_TIMEZONE_AUSTRALIA_BRISBANE             Timezone = "AUSTRALIA_BRISBANE"
	CLUSTER_TIMEZONE_AUSTRALIA_PERTH                Timezone = "AUSTRALIA_PERTH"
	CLUSTER_TIMEZONE_AUSTRALIA_SYDNEY               Timezone = "AUSTRALIA_SYDNEY"
	CLUSTER_TIMEZONE_EUROPE_AMSTERDAM               Timezone = "EUROPE_AMSTERDAM"
	CLUSTER_TIMEZONE_EUROPE_ATHENS                  Timezone = "EUROPE_ATHENS"
	CLUSTER_TIMEZONE_EUROPE_LONDON                  Timezone = "EUROPE_LONDON"
	CLUSTER_TIMEZONE_EUROPE_MOSCOW                  Timezone = "EUROPE_MOSCOW"
	CLUSTER_TIMEZONE_PACIFIC_AUCKLAND               Timezone = "PACIFIC_AUCKLAND"
	CLUSTER_TIMEZONE_PACIFIC_HONOLULU               Timezone = "PACIFIC_HONOLULU"
	CLUSTER_TIMEZONE_PACIFIC_MIDWAY                 Timezone = "PACIFIC_MIDWAY"
	CLUSTER_TIMEZONE_UTC                            Timezone = "UTC"
	CLUSTER_TIMEZONE_AFRICA_ABIDJAN                 Timezone = "AFRICA_ABIDJAN"
	CLUSTER_TIMEZONE_AFRICA_ALGIERS                 Timezone = "AFRICA_ALGIERS"
	CLUSTER_TIMEZONE_AFRICA_BISSAU                  Timezone = "AFRICA_BISSAU"
	CLUSTER_TIMEZONE_AFRICA_CEUTA                   Timezone = "AFRICA_CEUTA"
	CLUSTER_TIMEZONE_AFRICA_MAPUTO                  Timezone = "AFRICA_MAPUTO"
	CLUSTER_TIMEZONE_AFRICA_MONROVIA                Timezone = "AFRICA_MONROVIA"
	CLUSTER_TIMEZONE_AFRICA_NDJAMENA                Timezone = "AFRICA_NDJAMENA"
	CLUSTER_TIMEZONE_AFRICA_SAO_TOME                Timezone = "AFRICA_SAO_TOME"
	CLUSTER_TIMEZONE_AFRICA_TRIPOLI                 Timezone = "AFRICA_TRIPOLI"
	CLUSTER_TIMEZONE_AFRICA_TUNIS                   Timezone = "AFRICA_TUNIS"
	CLUSTER_TIMEZONE_AFRICA_WINDHOEK                Timezone = "AFRICA_WINDHOEK"
	CLUSTER_TIMEZONE_AMERICA_ADAK                   Timezone = "AMERICA_ADAK"
	CLUSTER_TIMEZONE_AMERICA_ARGENTINA_BUENOS_AIRES Timezone = "AMERICA_ARGENTINA_BUENOS_AIRES"
	CLUSTER_TIMEZONE_AMERICA_ARGENTINA_CATAMARCA    Timezone = "AMERICA_ARGENTINA_CATAMARCA"
	CLUSTER_TIMEZONE_AMERICA_ARGENTINA_CORDOBA      Timezone = "AMERICA_ARGENTINA_CORDOBA"
	CLUSTER_TIMEZONE_AMERICA_ARGENTINA_JUJUY        Timezone = "AMERICA_ARGENTINA_JUJUY"
	CLUSTER_TIMEZONE_AMERICA_ARGENTINA_LA_RIOJA     Timezone = "AMERICA_ARGENTINA_LA_RIOJA"
	CLUSTER_TIMEZONE_AMERICA_ARGENTINA_MENDOZA      Timezone = "AMERICA_ARGENTINA_MENDOZA"
	CLUSTER_TIMEZONE_AMERICA_ARGENTINA_RIO_GALLEGOS Timezone = "AMERICA_ARGENTINA_RIO_GALLEGOS"
	CLUSTER_TIMEZONE_AMERICA_ARGENTINA_SALTA        Timezone = "AMERICA_ARGENTINA_SALTA"
	CLUSTER_TIMEZONE_AMERICA_ARGENTINA_SAN_JUAN     Timezone = "AMERICA_ARGENTINA_SAN_JUAN"
	CLUSTER_TIMEZONE_AMERICA_ARGENTINA_SAN_LUIS     Timezone = "AMERICA_ARGENTINA_SAN_LUIS"
	CLUSTER_TIMEZONE_AMERICA_ARGENTINA_TUCUMAN      Timezone = "AMERICA_ARGENTINA_TUCUMAN"
	CLUSTER_TIMEZONE_AMERICA_ARGENTINA_USHUAIA      Timezone = "AMERICA_ARGENTINA_USHUAIA"
	CLUSTER_TIMEZONE_AMERICA_BAHIA                  Timezone = "AMERICA_BAHIA"
	CLUSTER_TIMEZONE_AMERICA_BELEM                  Timezone = "AMERICA_BELEM"
	CLUSTER_TIMEZONE_AMERICA_BELIZE                 Timezone = "AMERICA_BELIZE"
	CLUSTER_TIMEZONE_AMERICA_BOA_VISTA              Timezone = "AMERICA_BOA_VISTA"
	CLUSTER_TIMEZONE_AMERICA_BOISE                  Timezone = "AMERICA_BOISE"
	CLUSTER_TIMEZONE_AMERICA_CAMBRIDGE_BAY          Timezone = "AMERICA_CAMBRIDGE_BAY"
	CLUSTER_TIMEZONE_AMERICA_CAMPO_GRANDE           Timezone = "AMERICA_CAMPO_GRANDE"
	CLUSTER_TIMEZONE_AMERICA_CANCUN                 Timezone = "AMERICA_CANCUN"
	CLUSTER_TIMEZONE_AMERICA_CARACAS                Timezone = "AMERICA_CARACAS"
	CLUSTER_TIMEZONE_AMERICA_CAYENNE                Timezone = "AMERICA_CAYENNE"
	CLUSTER_TIMEZONE_AMERICA_CHIHUAHUA              Timezone = "AMERICA_CHIHUAHUA"
	CLUSTER_TIMEZONE_AMERICA_CIUDAD_JUAREZ          Timezone = "AMERICA_CIUDAD_JUAREZ"
	CLUSTER_TIMEZONE_AMERICA_CUIABA                 Timezone = "AMERICA_CUIABA"
	CLUSTER_TIMEZONE_AMERICA_DANMARKSHAVN           Timezone = "AMERICA_DANMARKSHAVN"
	CLUSTER_TIMEZONE_AMERICA_DAWSON                 Timezone = "AMERICA_DAWSON"
	CLUSTER_TIMEZONE_AMERICA_DAWSON_CREEK           Timezone = "AMERICA_DAWSON_CREEK"
	CLUSTER_TIMEZONE_AMERICA_DETROIT                Timezone = "AMERICA_DETROIT"
	CLUSTER_TIMEZONE_AMERICA_EDMONTON               Timezone = "AMERICA_EDMONTON"
	CLUSTER_TIMEZONE_AMERICA_EIRUNEPE               Timezone = "AMERICA_EIRUNEPE"
	CLUSTER_TIMEZONE_AMERICA_EL_SALVADOR            Timezone = "AMERICA_EL_SALVADOR"
	CLUSTER_TIMEZONE_AMERICA_FORT_NELSON            Timezone = "AMERICA_FORT_NELSON"
	CLUSTER_TIMEZONE_AMERICA_FORTALEZA              Timezone = "AMERICA_FORTALEZA"
	CLUSTER_TIMEZONE_AMERICA_GLACE_BAY              Timezone = "AMERICA_GLACE_BAY"
	CLUSTER_TIMEZONE_AMERICA_GOOSE_BAY              Timezone = "AMERICA_GOOSE_BAY"
	CLUSTER_TIMEZONE_AMERICA_GRAND_TURK             Timezone = "AMERICA_GRAND_TURK"
	CLUSTER_TIMEZONE_AMERICA_GUATEMALA              Timezone = "AMERICA_GUATEMALA"
	CLUSTER_TIMEZONE_AMERICA_GUAYAQUIL              Timezone = "AMERICA_GUAYAQUIL"
	CLUSTER_TIMEZONE_AMERICA_GUYANA                 Timezone = "AMERICA_GUYANA"
	CLUSTER_TIMEZONE_AMERICA_HALIFAX                Timezone = "AMERICA_HALIFAX"
	CLUSTER_TIMEZONE_AMERICA_HAVANA                 Timezone = "AMERICA_HAVANA"
	CLUSTER_TIMEZONE_AMERICA_INDIANA_INDIANAPOLIS   Timezone = "AMERICA_INDIANA_INDIANAPOLIS"
	CLUSTER_TIMEZONE_AMERICA_INDIANA_KNOX           Timezone = "AMERICA_INDIANA_KNOX"
	CLUSTER_TIMEZONE_AMERICA_INDIANA_MARENGO        Timezone = "AMERICA_INDIANA_MARENGO"
	CLUSTER_TIMEZONE_AMERICA_INDIANA_PETERSBURG     Timezone = "AMERICA_INDIANA_PETERSBURG"
	CLUSTER_TIMEZONE_AMERICA_INDIANA_TELL_CITY      Timezone = "AMERICA_INDIANA_TELL_CITY"
	CLUSTER_TIMEZONE_AMERICA_INDIANA_VEVAY          Timezone = "AMERICA_INDIANA_VEVAY"
	CLUSTER_TIMEZONE_AMERICA_INDIANA_VINCENNES      Timezone = "AMERICA_INDIANA_VINCENNES"
	CLUSTER_TIMEZONE_AMERICA_INDIANA_WINAMAC        Timezone = "AMERICA_INDIANA_WINAMAC"
	CLUSTER_TIMEZONE_AMERICA_INUVIK                 Timezone = "AMERICA_INUVIK"
	CLUSTER_TIMEZONE_AMERICA_IQALUIT                Timezone = "AMERICA_IQALUIT"
	CLUSTER_TIMEZONE_AMERICA_JAMAICA                Timezone = "AMERICA_JAMAICA"
	CLUSTER_TIMEZONE_AMERICA_JUNEAU                 Timezone = "AMERICA_JUNEAU"
	CLUSTER_TIMEZONE_AMERICA_KENTUCKY_LOUISVILLE    Timezone = "AMERICA_KENTUCKY_LOUISVILLE"
	CLUSTER_TIMEZONE_AMERICA_KENTUCKY_MONTICELLO    Timezone = "AMERICA_KENTUCKY_MONTICELLO"
	CLUSTER_TIMEZONE_AMERICA_LA_PAZ                 Timezone = "AMERICA_LA_PAZ"
	CLUSTER_TIMEZONE_AMERICA_LIMA                   Timezone = "AMERICA_LIMA"
	CLUSTER_TIMEZONE_AMERICA_MACEIO                 Timezone = "AMERICA_MACEIO"
	CLUSTER_TIMEZONE_AMERICA_MANAGUA                Timezone = "AMERICA_MANAGUA"
	CLUSTER_TIMEZONE_AMERICA_MANAUS                 Timezone = "AMERICA_MANAUS"
	CLUSTER_TIMEZONE_AMERICA_MARTINIQUE             Timezone = "AMERICA_MARTINIQUE"
	CLUSTER_TIMEZONE_AMERICA_MATAMOROS              Timezone = "AMERICA_MATAMOROS"
	CLUSTER_TIMEZONE_AMERICA_MENOMINEE              Timezone = "AMERICA_MENOMINEE"
	CLUSTER_TIMEZONE_AMERICA_MERIDA                 Timezone = "AMERICA_MERIDA"
	CLUSTER_TIMEZONE_AMERICA_METLAKATLA             Timezone = "AMERICA_METLAKATLA"
	CLUSTER_TIMEZONE_AMERICA_MIQUELON               Timezone = "AMERICA_MIQUELON"
	CLUSTER_TIMEZONE_AMERICA_MONCTON                Timezone = "AMERICA_MONCTON"
	CLUSTER_TIMEZONE_AMERICA_MONTERREY              Timezone = "AMERICA_MONTERREY"
	CLUSTER_TIMEZONE_AMERICA_MONTEVIDEO             Timezone = "AMERICA_MONTEVIDEO"
	CLUSTER_TIMEZONE_AMERICA_NOME                   Timezone = "AMERICA_NOME"
	CLUSTER_TIMEZONE_AMERICA_NORTH_DAKOTA_BEULAH    Timezone = "AMERICA_NORTH_DAKOTA_BEULAH"
	CLUSTER_TIMEZONE_AMERICA_NORTH_DAKOTA_CENTER    Timezone = "AMERICA_NORTH_DAKOTA_CENTER"
	CLUSTER_TIMEZONE_AMERICA_NORTH_DAKOTA_NEW_SALEM Timezone = "AMERICA_NORTH_DAKOTA_NEW_SALEM"
	CLUSTER_TIMEZONE_AMERICA_OJINAGA                Timezone = "AMERICA_OJINAGA"
	CLUSTER_TIMEZONE_AMERICA_PARAMARIBO             Timezone = "AMERICA_PARAMARIBO"
	CLUSTER_TIMEZONE_AMERICA_PORTO_VELHO            Timezone = "AMERICA_PORTO_VELHO"
	CLUSTER_TIMEZONE_AMERICA_PUERTO_RICO            Timezone = "AMERICA_PUERTO_RICO"
	CLUSTER_TIMEZONE_AMERICA_PUNTA_ARENAS           Timezone = "AMERICA_PUNTA_ARENAS"
	CLUSTER_TIMEZONE_AMERICA_RANKIN_INLET           Timezone = "AMERICA_RANKIN_INLET"
	CLUSTER_TIMEZONE_AMERICA_RECIFE                 Timezone = "AMERICA_RECIFE"
	CLUSTER_TIMEZONE_AMERICA_REGINA                 Timezone = "AMERICA_REGINA"
	CLUSTER_TIMEZONE_AMERICA_RESOLUTE               Timezone = "AMERICA_RESOLUTE"
	CLUSTER_TIMEZONE_AMERICA_RIO_BRANCO             Timezone = "AMERICA_RIO_BRANCO"
	CLUSTER_TIMEZONE_AMERICA_SANTAREM               Timezone = "AMERICA_SANTAREM"
	CLUSTER_TIMEZONE_AMERICA_SAO_PAULO              Timezone = "AMERICA_SAO_PAULO"
	CLUSTER_TIMEZONE_AMERICA_SCORESBYSUND           Timezone = "AMERICA_SCORESBYSUND"
	CLUSTER_TIMEZONE_AMERICA_SITKA                  Timezone = "AMERICA_SITKA"
	CLUSTER_TIMEZONE_AMERICA_SWIFT_CURRENT          Timezone = "AMERICA_SWIFT_CURRENT"
	CLUSTER_TIMEZONE_AMERICA_TEGUCIGALPA            Timezone = "AMERICA_TEGUCIGALPA"
	CLUSTER_TIMEZONE_AMERICA_THULE                  Timezone = "AMERICA_THULE"
	CLUSTER_TIMEZONE_AMERICA_TIJUANA                Timezone = "AMERICA_TIJUANA"
	CLUSTER_TIMEZONE_AMERICA_WHITEHORSE             Timezone = "AMERICA_WHITEHORSE"
	CLUSTER_TIMEZONE_AMERICA_WINNIPEG               Timezone = "AMERICA_WINNIPEG"
	CLUSTER_TIMEZONE_AMERICA_YAKUTAT                Timezone = "AMERICA_YAKUTAT"
)

// Product represents the valid cluster products.
type Product string

const (
	CDM          Product = "CDM"
	CLOUD_DIRECT Product = "CLOUD_DIRECT"
	DATOS        Product = "DATOS"
	POLARIS      Product = "POLARIS"
)

// ProductType represents the valid cluster product types.
type ProductType string

const (
	CLOUD      ProductType = "Cloud"
	RSC        ProductType = "Polaris"
	EXOCOMPUTE ProductType = "ExoCompute"
	ONPREM     ProductType = "OnPrem"
	ROBO       ProductType = "Robo"
	UNKNOWN    ProductType = "Unknown"
)

// Status represents the valid cluster statuses.
type Status string

const (
	ClusterConnected    Status = "Connected"
	ClusterDisconnected Status = "Disconnected"
	ClusterInitializing Status = "Initializing"
)

// SystemStatus represents the valid cluster system statuses.
type SystemStatus string

const (
	ClusterSystemStatusOK      SystemStatus = "OK"
	ClusterSystemStatusWARNING SystemStatus = "WARNING"
	ClusterSystemStatusFATAL   SystemStatus = "FATAL"
)

// SearchFilter represents the valid cluster search filters.
type SearchFilter struct {
	ID              []string       `json:"id"`
	Name            []string       `json:"name"`
	Type            []ProductType  `json:"type"`
	ConnectionState []Status       `json:"connectionState"`
	SystemStatus    []SystemStatus `json:"systemStatus"`
	ProductType     []Product      `json:"productType"`
}

// ClusterSortByEnum represents the valid sort by values.
type SortBy string

const (
	SortByEstimatedRunway  SortBy = "ESTIMATED_RUNWAY"
	SortByInstalledVersion SortBy = "INSTALLED_VERSION"
	SortByClusterName      SortBy = "ClusterName"
	SortByClusterType      SortBy = "ClusterType"
	SortByClusterLocation  SortBy = "CLUSTER_LOCATION"
	SortByRegisteredAt     SortBy = "RegisteredAt"
)
