package cluster

// Timezone represents the valid cluster timezones.
type Timezone string

const (
	TIMEZONE_UNSPECIFIED                    Timezone = "CLUSTER_TIMEZONE_UNSPECIFIED"
	TIMEZONE_AFRICA_JOHANNESBURG            Timezone = "AFRICA_JOHANNESBURG"
	TIMEZONE_AFRICA_LAGOS                   Timezone = "AFRICA_LAGOS"
	TIMEZONE_AFRICA_NAIROBI                 Timezone = "AFRICA_NAIROBI"
	TIMEZONE_AMERICA_ANCHORAGE              Timezone = "AMERICA_ANCHORAGE"
	TIMEZONE_AMERICA_ARAGUAINA              Timezone = "AMERICA_ARAGUAINA"
	TIMEZONE_AMERICA_ATIKOKAN               Timezone = "AMERICA_ATIKOKAN"
	TIMEZONE_AMERICA_BARBADOS               Timezone = "AMERICA_BARBADOS"
	TIMEZONE_AMERICA_BOGOTA                 Timezone = "AMERICA_BOGOTA"
	TIMEZONE_AMERICA_CHICAGO                Timezone = "AMERICA_CHICAGO"
	TIMEZONE_AMERICA_COSTA_RICA             Timezone = "AMERICA_COSTA_RICA"
	TIMEZONE_AMERICA_DENVER                 Timezone = "AMERICA_DENVER"
	TIMEZONE_AMERICA_LOS_ANGELES            Timezone = "AMERICA_LOS_ANGELES"
	TIMEZONE_AMERICA_MEXICO_CITY            Timezone = "AMERICA_MEXICO_CITY"
	TIMEZONE_AMERICA_NEW_YORK               Timezone = "AMERICA_NEW_YORK"
	TIMEZONE_AMERICA_NORONHA                Timezone = "AMERICA_NORONHA"
	TIMEZONE_AMERICA_PANAMA                 Timezone = "AMERICA_PANAMA"
	TIMEZONE_AMERICA_PHOENIX                Timezone = "AMERICA_PHOENIX"
	TIMEZONE_AMERICA_SANTIAGO               Timezone = "AMERICA_SANTIAGO"
	TIMEZONE_AMERICA_ST_JOHNS               Timezone = "AMERICA_ST_JOHNS"
	TIMEZONE_AMERICA_TORONTO                Timezone = "AMERICA_TORONTO"
	TIMEZONE_AMERICA_VANCOUVER              Timezone = "AMERICA_VANCOUVER"
	TIMEZONE_ASIA_BANGKOK                   Timezone = "ASIA_BANGKOK"
	TIMEZONE_ASIA_DHAKA                     Timezone = "ASIA_DHAKA"
	TIMEZONE_ASIA_DUBAI                     Timezone = "ASIA_DUBAI"
	TIMEZONE_ASIA_HONG_KONG                 Timezone = "ASIA_HONG_KONG"
	TIMEZONE_ASIA_KARACHI                   Timezone = "ASIA_KARACHI"
	TIMEZONE_ASIA_KATHMANDU                 Timezone = "ASIA_KATHMANDU"
	TIMEZONE_ASIA_KOLKATA                   Timezone = "ASIA_KOLKATA"
	TIMEZONE_ASIA_MAGADAN                   Timezone = "ASIA_MAGADAN"
	TIMEZONE_ASIA_SINGAPORE                 Timezone = "ASIA_SINGAPORE"
	TIMEZONE_ASIA_TOKYO                     Timezone = "ASIA_TOKYO"
	TIMEZONE_ATLANTIC_CAPE_VERDE            Timezone = "ATLANTIC_CAPE_VERDE"
	TIMEZONE_AUSTRALIA_ADELAIDE             Timezone = "AUSTRALIA_ADELAIDE"
	TIMEZONE_AUSTRALIA_BRISBANE             Timezone = "AUSTRALIA_BRISBANE"
	TIMEZONE_AUSTRALIA_PERTH                Timezone = "AUSTRALIA_PERTH"
	TIMEZONE_AUSTRALIA_SYDNEY               Timezone = "AUSTRALIA_SYDNEY"
	TIMEZONE_EUROPE_AMSTERDAM               Timezone = "EUROPE_AMSTERDAM"
	TIMEZONE_EUROPE_ATHENS                  Timezone = "EUROPE_ATHENS"
	TIMEZONE_EUROPE_LONDON                  Timezone = "EUROPE_LONDON"
	TIMEZONE_EUROPE_MOSCOW                  Timezone = "EUROPE_MOSCOW"
	TIMEZONE_PACIFIC_AUCKLAND               Timezone = "PACIFIC_AUCKLAND"
	TIMEZONE_PACIFIC_HONOLULU               Timezone = "PACIFIC_HONOLULU"
	TIMEZONE_PACIFIC_MIDWAY                 Timezone = "PACIFIC_MIDWAY"
	TIMEZONE_UTC                            Timezone = "UTC"
	TIMEZONE_AFRICA_ABIDJAN                 Timezone = "AFRICA_ABIDJAN"
	TIMEZONE_AFRICA_ALGIERS                 Timezone = "AFRICA_ALGIERS"
	TIMEZONE_AFRICA_BISSAU                  Timezone = "AFRICA_BISSAU"
	TIMEZONE_AFRICA_CEUTA                   Timezone = "AFRICA_CEUTA"
	TIMEZONE_AFRICA_MAPUTO                  Timezone = "AFRICA_MAPUTO"
	TIMEZONE_AFRICA_MONROVIA                Timezone = "AFRICA_MONROVIA"
	TIMEZONE_AFRICA_NDJAMENA                Timezone = "AFRICA_NDJAMENA"
	TIMEZONE_AFRICA_SAO_TOME                Timezone = "AFRICA_SAO_TOME"
	TIMEZONE_AFRICA_TRIPOLI                 Timezone = "AFRICA_TRIPOLI"
	TIMEZONE_AFRICA_TUNIS                   Timezone = "AFRICA_TUNIS"
	TIMEZONE_AFRICA_WINDHOEK                Timezone = "AFRICA_WINDHOEK"
	TIMEZONE_AMERICA_ADAK                   Timezone = "AMERICA_ADAK"
	TIMEZONE_AMERICA_ARGENTINA_BUENOS_AIRES Timezone = "AMERICA_ARGENTINA_BUENOS_AIRES"
	TIMEZONE_AMERICA_ARGENTINA_CATAMARCA    Timezone = "AMERICA_ARGENTINA_CATAMARCA"
	TIMEZONE_AMERICA_ARGENTINA_CORDOBA      Timezone = "AMERICA_ARGENTINA_CORDOBA"
	TIMEZONE_AMERICA_ARGENTINA_JUJUY        Timezone = "AMERICA_ARGENTINA_JUJUY"
	TIMEZONE_AMERICA_ARGENTINA_LA_RIOJA     Timezone = "AMERICA_ARGENTINA_LA_RIOJA"
	TIMEZONE_AMERICA_ARGENTINA_MENDOZA      Timezone = "AMERICA_ARGENTINA_MENDOZA"
	TIMEZONE_AMERICA_ARGENTINA_RIO_GALLEGOS Timezone = "AMERICA_ARGENTINA_RIO_GALLEGOS"
	TIMEZONE_AMERICA_ARGENTINA_SALTA        Timezone = "AMERICA_ARGENTINA_SALTA"
	TIMEZONE_AMERICA_ARGENTINA_SAN_JUAN     Timezone = "AMERICA_ARGENTINA_SAN_JUAN"
	TIMEZONE_AMERICA_ARGENTINA_SAN_LUIS     Timezone = "AMERICA_ARGENTINA_SAN_LUIS"
	TIMEZONE_AMERICA_ARGENTINA_TUCUMAN      Timezone = "AMERICA_ARGENTINA_TUCUMAN"
	TIMEZONE_AMERICA_ARGENTINA_USHUAIA      Timezone = "AMERICA_ARGENTINA_USHUAIA"
	TIMEZONE_AMERICA_BAHIA                  Timezone = "AMERICA_BAHIA"
	TIMEZONE_AMERICA_BELEM                  Timezone = "AMERICA_BELEM"
	TIMEZONE_AMERICA_BELIZE                 Timezone = "AMERICA_BELIZE"
	TIMEZONE_AMERICA_BOA_VISTA              Timezone = "AMERICA_BOA_VISTA"
	TIMEZONE_AMERICA_BOISE                  Timezone = "AMERICA_BOISE"
	TIMEZONE_AMERICA_CAMBRIDGE_BAY          Timezone = "AMERICA_CAMBRIDGE_BAY"
	TIMEZONE_AMERICA_CAMPO_GRANDE           Timezone = "AMERICA_CAMPO_GRANDE"
	TIMEZONE_AMERICA_CANCUN                 Timezone = "AMERICA_CANCUN"
	TIMEZONE_AMERICA_CARACAS                Timezone = "AMERICA_CARACAS"
	TIMEZONE_AMERICA_CAYENNE                Timezone = "AMERICA_CAYENNE"
	TIMEZONE_AMERICA_CHIHUAHUA              Timezone = "AMERICA_CHIHUAHUA"
	TIMEZONE_AMERICA_CIUDAD_JUAREZ          Timezone = "AMERICA_CIUDAD_JUAREZ"
	TIMEZONE_AMERICA_CUIABA                 Timezone = "AMERICA_CUIABA"
	TIMEZONE_AMERICA_DANMARKSHAVN           Timezone = "AMERICA_DANMARKSHAVN"
	TIMEZONE_AMERICA_DAWSON                 Timezone = "AMERICA_DAWSON"
	TIMEZONE_AMERICA_DAWSON_CREEK           Timezone = "AMERICA_DAWSON_CREEK"
	TIMEZONE_AMERICA_DETROIT                Timezone = "AMERICA_DETROIT"
	TIMEZONE_AMERICA_EDMONTON               Timezone = "AMERICA_EDMONTON"
	TIMEZONE_AMERICA_EIRUNEPE               Timezone = "AMERICA_EIRUNEPE"
	TIMEZONE_AMERICA_EL_SALVADOR            Timezone = "AMERICA_EL_SALVADOR"
	TIMEZONE_AMERICA_FORT_NELSON            Timezone = "AMERICA_FORT_NELSON"
	TIMEZONE_AMERICA_FORTALEZA              Timezone = "AMERICA_FORTALEZA"
	TIMEZONE_AMERICA_GLACE_BAY              Timezone = "AMERICA_GLACE_BAY"
	TIMEZONE_AMERICA_GOOSE_BAY              Timezone = "AMERICA_GOOSE_BAY"
	TIMEZONE_AMERICA_GRAND_TURK             Timezone = "AMERICA_GRAND_TURK"
	TIMEZONE_AMERICA_GUATEMALA              Timezone = "AMERICA_GUATEMALA"
	TIMEZONE_AMERICA_GUAYAQUIL              Timezone = "AMERICA_GUAYAQUIL"
	TIMEZONE_AMERICA_GUYANA                 Timezone = "AMERICA_GUYANA"
	TIMEZONE_AMERICA_HALIFAX                Timezone = "AMERICA_HALIFAX"
	TIMEZONE_AMERICA_HAVANA                 Timezone = "AMERICA_HAVANA"
	TIMEZONE_AMERICA_INDIANA_INDIANAPOLIS   Timezone = "AMERICA_INDIANA_INDIANAPOLIS"
	TIMEZONE_AMERICA_INDIANA_KNOX           Timezone = "AMERICA_INDIANA_KNOX"
	TIMEZONE_AMERICA_INDIANA_MARENGO        Timezone = "AMERICA_INDIANA_MARENGO"
	TIMEZONE_AMERICA_INDIANA_PETERSBURG     Timezone = "AMERICA_INDIANA_PETERSBURG"
	TIMEZONE_AMERICA_INDIANA_TELL_CITY      Timezone = "AMERICA_INDIANA_TELL_CITY"
	TIMEZONE_AMERICA_INDIANA_VEVAY          Timezone = "AMERICA_INDIANA_VEVAY"
	TIMEZONE_AMERICA_INDIANA_VINCENNES      Timezone = "AMERICA_INDIANA_VINCENNES"
	TIMEZONE_AMERICA_INDIANA_WINAMAC        Timezone = "AMERICA_INDIANA_WINAMAC"
	TIMEZONE_AMERICA_INUVIK                 Timezone = "AMERICA_INUVIK"
	TIMEZONE_AMERICA_IQALUIT                Timezone = "AMERICA_IQALUIT"
	TIMEZONE_AMERICA_JAMAICA                Timezone = "AMERICA_JAMAICA"
	TIMEZONE_AMERICA_JUNEAU                 Timezone = "AMERICA_JUNEAU"
	TIMEZONE_AMERICA_KENTUCKY_LOUISVILLE    Timezone = "AMERICA_KENTUCKY_LOUISVILLE"
	TIMEZONE_AMERICA_KENTUCKY_MONTICELLO    Timezone = "AMERICA_KENTUCKY_MONTICELLO"
	TIMEZONE_AMERICA_LA_PAZ                 Timezone = "AMERICA_LA_PAZ"
	TIMEZONE_AMERICA_LIMA                   Timezone = "AMERICA_LIMA"
	TIMEZONE_AMERICA_MACEIO                 Timezone = "AMERICA_MACEIO"
	TIMEZONE_AMERICA_MANAGUA                Timezone = "AMERICA_MANAGUA"
	TIMEZONE_AMERICA_MANAUS                 Timezone = "AMERICA_MANAUS"
	TIMEZONE_AMERICA_MARTINIQUE             Timezone = "AMERICA_MARTINIQUE"
	TIMEZONE_AMERICA_MATAMOROS              Timezone = "AMERICA_MATAMOROS"
	TIMEZONE_AMERICA_MENOMINEE              Timezone = "AMERICA_MENOMINEE"
	TIMEZONE_AMERICA_MERIDA                 Timezone = "AMERICA_MERIDA"
	TIMEZONE_AMERICA_METLAKATLA             Timezone = "AMERICA_METLAKATLA"
	TIMEZONE_AMERICA_MIQUELON               Timezone = "AMERICA_MIQUELON"
	TIMEZONE_AMERICA_MONCTON                Timezone = "AMERICA_MONCTON"
	TIMEZONE_AMERICA_MONTERREY              Timezone = "AMERICA_MONTERREY"
	TIMEZONE_AMERICA_MONTEVIDEO             Timezone = "AMERICA_MONTEVIDEO"
	TIMEZONE_AMERICA_NOME                   Timezone = "AMERICA_NOME"
	TIMEZONE_AMERICA_NORTH_DAKOTA_BEULAH    Timezone = "AMERICA_NORTH_DAKOTA_BEULAH"
	TIMEZONE_AMERICA_NORTH_DAKOTA_CENTER    Timezone = "AMERICA_NORTH_DAKOTA_CENTER"
	TIMEZONE_AMERICA_NORTH_DAKOTA_NEW_SALEM Timezone = "AMERICA_NORTH_DAKOTA_NEW_SALEM"
	TIMEZONE_AMERICA_OJINAGA                Timezone = "AMERICA_OJINAGA"
	TIMEZONE_AMERICA_PARAMARIBO             Timezone = "AMERICA_PARAMARIBO"
	TIMEZONE_AMERICA_PORTO_VELHO            Timezone = "AMERICA_PORTO_VELHO"
	TIMEZONE_AMERICA_PUERTO_RICO            Timezone = "AMERICA_PUERTO_RICO"
	TIMEZONE_AMERICA_PUNTA_ARENAS           Timezone = "AMERICA_PUNTA_ARENAS"
	TIMEZONE_AMERICA_RANKIN_INLET           Timezone = "AMERICA_RANKIN_INLET"
	TIMEZONE_AMERICA_RECIFE                 Timezone = "AMERICA_RECIFE"
	TIMEZONE_AMERICA_REGINA                 Timezone = "AMERICA_REGINA"
	TIMEZONE_AMERICA_RESOLUTE               Timezone = "AMERICA_RESOLUTE"
	TIMEZONE_AMERICA_RIO_BRANCO             Timezone = "AMERICA_RIO_BRANCO"
	TIMEZONE_AMERICA_SANTAREM               Timezone = "AMERICA_SANTAREM"
	TIMEZONE_AMERICA_SAO_PAULO              Timezone = "AMERICA_SAO_PAULO"
	TIMEZONE_AMERICA_SCORESBYSUND           Timezone = "AMERICA_SCORESBYSUND"
	TIMEZONE_AMERICA_SITKA                  Timezone = "AMERICA_SITKA"
	TIMEZONE_AMERICA_SWIFT_CURRENT          Timezone = "AMERICA_SWIFT_CURRENT"
	TIMEZONE_AMERICA_TEGUCIGALPA            Timezone = "AMERICA_TEGUCIGALPA"
	TIMEZONE_AMERICA_THULE                  Timezone = "AMERICA_THULE"
	TIMEZONE_AMERICA_TIJUANA                Timezone = "AMERICA_TIJUANA"
	TIMEZONE_AMERICA_WHITEHORSE             Timezone = "AMERICA_WHITEHORSE"
	TIMEZONE_AMERICA_WINNIPEG               Timezone = "AMERICA_WINNIPEG"
	TIMEZONE_AMERICA_YAKUTAT                Timezone = "AMERICA_YAKUTAT"
)

// Product represents the valid cluster products.
type Product string

const (
	CDM          Product = "CDM"
	CLOUD_DIRECT Product = "CLOUD_DIRECT"
	DATOS        Product = "DATOS"
	POLARIS      Product = "POLARIS"
)

// ProductType represents the valid cluster product types.
type ProductType string

const (
	CLOUD      ProductType = "Cloud"
	RSC        ProductType = "Polaris"
	EXOCOMPUTE ProductType = "ExoCompute"
	ONPREM     ProductType = "OnPrem"
	ROBO       ProductType = "Robo"
	UNKNOWN    ProductType = "Unknown"
)

// Status represents the valid cluster statuses.
type Status string

const (
	Connected    Status = "Connected"
	Disconnected Status = "Disconnected"
	Initializing Status = "Initializing"
)

// SystemStatus represents the valid cluster system statuses.
type SystemStatus string

const (
	SystemStatusOK      SystemStatus = "OK"
	SystemStatusWARNING SystemStatus = "WARNING"
	SystemStatusFATAL   SystemStatus = "FATAL"
)

// SearchFilter represents the valid cluster search filters.
type SearchFilter struct {
	ID              []string       `json:"id"`
	Name            []string       `json:"name"`
	Type            []ProductType  `json:"type"`
	ConnectionState []Status       `json:"connectionState"`
	SystemStatus    []SystemStatus `json:"systemStatus"`
	ProductType     []Product      `json:"productType"`
}

// SortByEnum represents the valid sort by values.
type SortBy string

const (
	SortByEstimatedRunway  SortBy = "ESTIMATED_RUNWAY"
	SortByInstalledVersion SortBy = "INSTALLED_VERSION"
	SortByClusterName      SortBy = "ClusterName"
	SortByClusterType      SortBy = "ClusterType"
	SortByClusterLocation  SortBy = "CLUSTER_LOCATION"
	SortByRegisteredAt     SortBy = "RegisteredAt"
)
