package cluster

import "strings"

// Timezone represents the valid cluster timezones.
type Timezone string

const (
	TIMEZONE_UNSPECIFIED                    Timezone = "CLUSTER_TIMEZONE_UNSPECIFIED"
	TIMEZONE_AFRICA_JOHANNESBURG            Timezone = "CLUSTER_TIMEZONE_AFRICA_JOHANNESBURG"
	TIMEZONE_AFRICA_LAGOS                   Timezone = "CLUSTER_TIMEZONE_AFRICA_LAGOS"
	TIMEZONE_AFRICA_NAIROBI                 Timezone = "CLUSTER_TIMEZONE_AFRICA_NAIROBI"
	TIMEZONE_AMERICA_ANCHORAGE              Timezone = "CLUSTER_TIMEZONE_AMERICA_ANCHORAGE"
	TIMEZONE_AMERICA_ARAGUAINA              Timezone = "CLUSTER_TIMEZONE_AMERICA_ARAGUAINA"
	TIMEZONE_AMERICA_ATIKOKAN               Timezone = "CLUSTER_TIMEZONE_AMERICA_ATIKOKAN"
	TIMEZONE_AMERICA_BARBADOS               Timezone = "CLUSTER_TIMEZONE_AMERICA_BARBADOS"
	TIMEZONE_AMERICA_BOGOTA                 Timezone = "CLUSTER_TIMEZONE_AMERICA_BOGOTA"
	TIMEZONE_AMERICA_CHICAGO                Timezone = "CLUSTER_TIMEZONE_AMERICA_CHICAGO"
	TIMEZONE_AMERICA_COSTA_RICA             Timezone = "CLUSTER_TIMEZONE_AMERICA_COSTA_RICA"
	TIMEZONE_AMERICA_DENVER                 Timezone = "CLUSTER_TIMEZONE_AMERICA_DENVER"
	TIMEZONE_AMERICA_LOS_ANGELES            Timezone = "CLUSTER_TIMEZONE_AMERICA_LOS_ANGELES"
	TIMEZONE_AMERICA_MEXICO_CITY            Timezone = "CLUSTER_TIMEZONE_AMERICA_MEXICO_CITY"
	TIMEZONE_AMERICA_NEW_YORK               Timezone = "CLUSTER_TIMEZONE_AMERICA_NEW_YORK"
	TIMEZONE_AMERICA_NORONHA                Timezone = "CLUSTER_TIMEZONE_AMERICA_NORONHA"
	TIMEZONE_AMERICA_PANAMA                 Timezone = "CLUSTER_TIMEZONE_AMERICA_PANAMA"
	TIMEZONE_AMERICA_PHOENIX                Timezone = "CLUSTER_TIMEZONE_AMERICA_PHOENIX"
	TIMEZONE_AMERICA_SANTIAGO               Timezone = "CLUSTER_TIMEZONE_AMERICA_SANTIAGO"
	TIMEZONE_AMERICA_ST_JOHNS               Timezone = "CLUSTER_TIMEZONE_AMERICA_ST_JOHNS"
	TIMEZONE_AMERICA_TORONTO                Timezone = "CLUSTER_TIMEZONE_AMERICA_TORONTO"
	TIMEZONE_AMERICA_VANCOUVER              Timezone = "CLUSTER_TIMEZONE_AMERICA_VANCOUVER"
	TIMEZONE_ASIA_BANGKOK                   Timezone = "CLUSTER_TIMEZONE_ASIA_BANGKOK"
	TIMEZONE_ASIA_DHAKA                     Timezone = "CLUSTER_TIMEZONE_ASIA_DHAKA"
	TIMEZONE_ASIA_DUBAI                     Timezone = "CLUSTER_TIMEZONE_ASIA_DUBAI"
	TIMEZONE_ASIA_HONG_KONG                 Timezone = "CLUSTER_TIMEZONE_ASIA_HONG_KONG"
	TIMEZONE_ASIA_KARACHI                   Timezone = "CLUSTER_TIMEZONE_ASIA_KARACHI"
	TIMEZONE_ASIA_KATHMANDU                 Timezone = "CLUSTER_TIMEZONE_ASIA_KATHMANDU"
	TIMEZONE_ASIA_KOLKATA                   Timezone = "CLUSTER_TIMEZONE_ASIA_KOLKATA"
	TIMEZONE_ASIA_MAGADAN                   Timezone = "CLUSTER_TIMEZONE_ASIA_MAGADAN"
	TIMEZONE_ASIA_SINGAPORE                 Timezone = "CLUSTER_TIMEZONE_ASIA_SINGAPORE"
	TIMEZONE_ASIA_TOKYO                     Timezone = "CLUSTER_TIMEZONE_ASIA_TOKYO"
	TIMEZONE_ATLANTIC_CAPE_VERDE            Timezone = "CLUSTER_TIMEZONE_ATLANTIC_CAPE_VERDE"
	TIMEZONE_AUSTRALIA_ADELAIDE             Timezone = "CLUSTER_TIMEZONE_AUSTRALIA_ADELAIDE"
	TIMEZONE_AUSTRALIA_BRISBANE             Timezone = "CLUSTER_TIMEZONE_AUSTRALIA_BRISBANE"
	TIMEZONE_AUSTRALIA_PERTH                Timezone = "CLUSTER_TIMEZONE_AUSTRALIA_PERTH"
	TIMEZONE_AUSTRALIA_SYDNEY               Timezone = "CLUSTER_TIMEZONE_AUSTRALIA_SYDNEY"
	TIMEZONE_EUROPE_AMSTERDAM               Timezone = "CLUSTER_TIMEZONE_EUROPE_AMSTERDAM"
	TIMEZONE_EUROPE_ATHENS                  Timezone = "CLUSTER_TIMEZONE_EUROPE_ATHENS"
	TIMEZONE_EUROPE_LONDON                  Timezone = "CLUSTER_TIMEZONE_EUROPE_LONDON"
	TIMEZONE_EUROPE_MOSCOW                  Timezone = "CLUSTER_TIMEZONE_EUROPE_MOSCOW"
	TIMEZONE_PACIFIC_AUCKLAND               Timezone = "CLUSTER_TIMEZONE_PACIFIC_AUCKLAND"
	TIMEZONE_PACIFIC_HONOLULU               Timezone = "CLUSTER_TIMEZONE_PACIFIC_HONOLULU"
	TIMEZONE_PACIFIC_MIDWAY                 Timezone = "CLUSTER_TIMEZONE_PACIFIC_MIDWAY"
	TIMEZONE_UTC                            Timezone = "CLUSTER_TIMEZONE_UTC"
	TIMEZONE_AFRICA_ABIDJAN                 Timezone = "CLUSTER_TIMEZONE_AFRICA_ABIDJAN"
	TIMEZONE_AFRICA_ALGIERS                 Timezone = "CLUSTER_TIMEZONE_AFRICA_ALGIERS"
	TIMEZONE_AFRICA_BISSAU                  Timezone = "CLUSTER_TIMEZONE_AFRICA_BISSAU"
	TIMEZONE_AFRICA_CEUTA                   Timezone = "CLUSTER_TIMEZONE_AFRICA_CEUTA"
	TIMEZONE_AFRICA_MAPUTO                  Timezone = "CLUSTER_TIMEZONE_AFRICA_MAPUTO"
	TIMEZONE_AFRICA_MONROVIA                Timezone = "CLUSTER_TIMEZONE_AFRICA_MONROVIA"
	TIMEZONE_AFRICA_NDJAMENA                Timezone = "CLUSTER_TIMEZONE_AFRICA_NDJAMENA"
	TIMEZONE_AFRICA_SAO_TOME                Timezone = "CLUSTER_TIMEZONE_AFRICA_SAO_TOME"
	TIMEZONE_AFRICA_TRIPOLI                 Timezone = "CLUSTER_TIMEZONE_AFRICA_TRIPOLI"
	TIMEZONE_AFRICA_TUNIS                   Timezone = "CLUSTER_TIMEZONE_AFRICA_TUNIS"
	TIMEZONE_AFRICA_WINDHOEK                Timezone = "CLUSTER_TIMEZONE_AFRICA_WINDHOEK"
	TIMEZONE_AMERICA_ADAK                   Timezone = "CLUSTER_TIMEZONE_AMERICA_ADAK"
	TIMEZONE_AMERICA_ARGENTINA_BUENOS_AIRES Timezone = "CLUSTER_TIMEZONE_AMERICA_ARGENTINA_BUENOS_AIRES"
	TIMEZONE_AMERICA_ARGENTINA_CATAMARCA    Timezone = "CLUSTER_TIMEZONE_AMERICA_ARGENTINA_CATAMARCA"
	TIMEZONE_AMERICA_ARGENTINA_CORDOBA      Timezone = "CLUSTER_TIMEZONE_AMERICA_ARGENTINA_CORDOBA"
	TIMEZONE_AMERICA_ARGENTINA_JUJUY        Timezone = "CLUSTER_TIMEZONE_AMERICA_ARGENTINA_JUJUY"
	TIMEZONE_AMERICA_ARGENTINA_LA_RIOJA     Timezone = "CLUSTER_TIMEZONE_AMERICA_ARGENTINA_LA_RIOJA"
	TIMEZONE_AMERICA_ARGENTINA_MENDOZA      Timezone = "CLUSTER_TIMEZONE_AMERICA_ARGENTINA_MENDOZA"
	TIMEZONE_AMERICA_ARGENTINA_RIO_GALLEGOS Timezone = "CLUSTER_TIMEZONE_AMERICA_ARGENTINA_RIO_GALLEGOS"
	TIMEZONE_AMERICA_ARGENTINA_SALTA        Timezone = "CLUSTER_TIMEZONE_AMERICA_ARGENTINA_SALTA"
	TIMEZONE_AMERICA_ARGENTINA_SAN_JUAN     Timezone = "CLUSTER_TIMEZONE_AMERICA_ARGENTINA_SAN_JUAN"
	TIMEZONE_AMERICA_ARGENTINA_SAN_LUIS     Timezone = "CLUSTER_TIMEZONE_AMERICA_ARGENTINA_SAN_LUIS"
	TIMEZONE_AMERICA_ARGENTINA_TUCUMAN      Timezone = "CLUSTER_TIMEZONE_AMERICA_ARGENTINA_TUCUMAN"
	TIMEZONE_AMERICA_ARGENTINA_USHUAIA      Timezone = "CLUSTER_TIMEZONE_AMERICA_ARGENTINA_USHUAIA"
	TIMEZONE_AMERICA_BAHIA                  Timezone = "CLUSTER_TIMEZONE_AMERICA_BAHIA"
	TIMEZONE_AMERICA_BELEM                  Timezone = "CLUSTER_TIMEZONE_AMERICA_BELEM"
	TIMEZONE_AMERICA_BELIZE                 Timezone = "CLUSTER_TIMEZONE_AMERICA_BELIZE"
	TIMEZONE_AMERICA_BOA_VISTA              Timezone = "CLUSTER_TIMEZONE_AMERICA_BOA_VISTA"
	TIMEZONE_AMERICA_BOISE                  Timezone = "CLUSTER_TIMEZONE_AMERICA_BOISE"
	TIMEZONE_AMERICA_CAMBRIDGE_BAY          Timezone = "CLUSTER_TIMEZONE_AMERICA_CAMBRIDGE_BAY"
	TIMEZONE_AMERICA_CAMPO_GRANDE           Timezone = "CLUSTER_TIMEZONE_AMERICA_CAMPO_GRANDE"
	TIMEZONE_AMERICA_CANCUN                 Timezone = "CLUSTER_TIMEZONE_AMERICA_CANCUN"
	TIMEZONE_AMERICA_CARACAS                Timezone = "CLUSTER_TIMEZONE_AMERICA_CARACAS"
	TIMEZONE_AMERICA_CAYENNE                Timezone = "CLUSTER_TIMEZONE_AMERICA_CAYENNE"
	TIMEZONE_AMERICA_CHIHUAHUA              Timezone = "CLUSTER_TIMEZONE_AMERICA_CHIHUAHUA"
	TIMEZONE_AMERICA_CIUDAD_JUAREZ          Timezone = "CLUSTER_TIMEZONE_AMERICA_CIUDAD_JUAREZ"
	TIMEZONE_AMERICA_CUIABA                 Timezone = "CLUSTER_TIMEZONE_AMERICA_CUIABA"
	TIMEZONE_AMERICA_DANMARKSHAVN           Timezone = "CLUSTER_TIMEZONE_AMERICA_DANMARKSHAVN"
	TIMEZONE_AMERICA_DAWSON                 Timezone = "CLUSTER_TIMEZONE_AMERICA_DAWSON"
	TIMEZONE_AMERICA_DAWSON_CREEK           Timezone = "CLUSTER_TIMEZONE_AMERICA_DAWSON_CREEK"
	TIMEZONE_AMERICA_DETROIT                Timezone = "CLUSTER_TIMEZONE_AMERICA_DETROIT"
	TIMEZONE_AMERICA_EDMONTON               Timezone = "CLUSTER_TIMEZONE_AMERICA_EDMONTON"
	TIMEZONE_AMERICA_EIRUNEPE               Timezone = "CLUSTER_TIMEZONE_AMERICA_EIRUNEPE"
	TIMEZONE_AMERICA_EL_SALVADOR            Timezone = "CLUSTER_TIMEZONE_AMERICA_EL_SALVADOR"
	TIMEZONE_AMERICA_FORT_NELSON            Timezone = "CLUSTER_TIMEZONE_AMERICA_FORT_NELSON"
	TIMEZONE_AMERICA_FORTALEZA              Timezone = "CLUSTER_TIMEZONE_AMERICA_FORTALEZA"
	TIMEZONE_AMERICA_GLACE_BAY              Timezone = "CLUSTER_TIMEZONE_AMERICA_GLACE_BAY"
	TIMEZONE_AMERICA_GOOSE_BAY              Timezone = "CLUSTER_TIMEZONE_AMERICA_GOOSE_BAY"
	TIMEZONE_AMERICA_GRAND_TURK             Timezone = "CLUSTER_TIMEZONE_AMERICA_GRAND_TURK"
	TIMEZONE_AMERICA_GUATEMALA              Timezone = "CLUSTER_TIMEZONE_AMERICA_GUATEMALA"
	TIMEZONE_AMERICA_GUAYAQUIL              Timezone = "CLUSTER_TIMEZONE_AMERICA_GUAYAQUIL"
	TIMEZONE_AMERICA_GUYANA                 Timezone = "CLUSTER_TIMEZONE_AMERICA_GUYANA"
	TIMEZONE_AMERICA_HALIFAX                Timezone = "CLUSTER_TIMEZONE_AMERICA_HALIFAX"
	TIMEZONE_AMERICA_HAVANA                 Timezone = "CLUSTER_TIMEZONE_AMERICA_HAVANA"
	TIMEZONE_AMERICA_INDIANA_INDIANAPOLIS   Timezone = "CLUSTER_TIMEZONE_AMERICA_INDIANA_INDIANAPOLIS"
	TIMEZONE_AMERICA_INDIANA_KNOX           Timezone = "CLUSTER_TIMEZONE_AMERICA_INDIANA_KNOX"
	TIMEZONE_AMERICA_INDIANA_MARENGO        Timezone = "CLUSTER_TIMEZONE_AMERICA_INDIANA_MARENGO"
	TIMEZONE_AMERICA_INDIANA_PETERSBURG     Timezone = "CLUSTER_TIMEZONE_AMERICA_INDIANA_PETERSBURG"
	TIMEZONE_AMERICA_INDIANA_TELL_CITY      Timezone = "CLUSTER_TIMEZONE_AMERICA_INDIANA_TELL_CITY"
	TIMEZONE_AMERICA_INDIANA_VEVAY          Timezone = "CLUSTER_TIMEZONE_AMERICA_INDIANA_VEVAY"
	TIMEZONE_AMERICA_INDIANA_VINCENNES      Timezone = "CLUSTER_TIMEZONE_AMERICA_INDIANA_VINCENNES"
	TIMEZONE_AMERICA_INDIANA_WINAMAC        Timezone = "CLUSTER_TIMEZONE_AMERICA_INDIANA_WINAMAC"
	TIMEZONE_AMERICA_INUVIK                 Timezone = "CLUSTER_TIMEZONE_AMERICA_INUVIK"
	TIMEZONE_AMERICA_IQALUIT                Timezone = "CLUSTER_TIMEZONE_AMERICA_IQALUIT"
	TIMEZONE_AMERICA_JAMAICA                Timezone = "CLUSTER_TIMEZONE_AMERICA_JAMAICA"
	TIMEZONE_AMERICA_JUNEAU                 Timezone = "CLUSTER_TIMEZONE_AMERICA_JUNEAU"
	TIMEZONE_AMERICA_KENTUCKY_LOUISVILLE    Timezone = "CLUSTER_TIMEZONE_AMERICA_KENTUCKY_LOUISVILLE"
	TIMEZONE_AMERICA_KENTUCKY_MONTICELLO    Timezone = "CLUSTER_TIMEZONE_AMERICA_KENTUCKY_MONTICELLO"
	TIMEZONE_AMERICA_LA_PAZ                 Timezone = "CLUSTER_TIMEZONE_AMERICA_LA_PAZ"
	TIMEZONE_AMERICA_LIMA                   Timezone = "CLUSTER_TIMEZONE_AMERICA_LIMA"
	TIMEZONE_AMERICA_MACEIO                 Timezone = "CLUSTER_TIMEZONE_AMERICA_MACEIO"
	TIMEZONE_AMERICA_MANAGUA                Timezone = "CLUSTER_TIMEZONE_AMERICA_MANAGUA"
	TIMEZONE_AMERICA_MANAUS                 Timezone = "CLUSTER_TIMEZONE_AMERICA_MANAUS"
	TIMEZONE_AMERICA_MARTINIQUE             Timezone = "CLUSTER_TIMEZONE_AMERICA_MARTINIQUE"
	TIMEZONE_AMERICA_MATAMOROS              Timezone = "CLUSTER_TIMEZONE_AMERICA_MATAMOROS"
	TIMEZONE_AMERICA_MENOMINEE              Timezone = "CLUSTER_TIMEZONE_AMERICA_MENOMINEE"
	TIMEZONE_AMERICA_MERIDA                 Timezone = "CLUSTER_TIMEZONE_AMERICA_MERIDA"
	TIMEZONE_AMERICA_METLAKATLA             Timezone = "CLUSTER_TIMEZONE_AMERICA_METLAKATLA"
	TIMEZONE_AMERICA_MIQUELON               Timezone = "CLUSTER_TIMEZONE_AMERICA_MIQUELON"
	TIMEZONE_AMERICA_MONCTON                Timezone = "CLUSTER_TIMEZONE_AMERICA_MONCTON"
	TIMEZONE_AMERICA_MONTERREY              Timezone = "CLUSTER_TIMEZONE_AMERICA_MONTERREY"
	TIMEZONE_AMERICA_MONTEVIDEO             Timezone = "CLUSTER_TIMEZONE_AMERICA_MONTEVIDEO"
	TIMEZONE_AMERICA_NOME                   Timezone = "CLUSTER_TIMEZONE_AMERICA_NOME"
	TIMEZONE_AMERICA_NORTH_DAKOTA_BEULAH    Timezone = "CLUSTER_TIMEZONE_AMERICA_NORTH_DAKOTA_BEULAH"
	TIMEZONE_AMERICA_NORTH_DAKOTA_CENTER    Timezone = "CLUSTER_TIMEZONE_AMERICA_NORTH_DAKOTA_CENTER"
	TIMEZONE_AMERICA_NORTH_DAKOTA_NEW_SALEM Timezone = "CLUSTER_TIMEZONE_AMERICA_NORTH_DAKOTA_NEW_SALEM"
	TIMEZONE_AMERICA_OJINAGA                Timezone = "CLUSTER_TIMEZONE_AMERICA_OJINAGA"
	TIMEZONE_AMERICA_PARAMARIBO             Timezone = "CLUSTER_TIMEZONE_AMERICA_PARAMARIBO"
	TIMEZONE_AMERICA_PORTO_VELHO            Timezone = "CLUSTER_TIMEZONE_AMERICA_PORTO_VELHO"
	TIMEZONE_AMERICA_PUERTO_RICO            Timezone = "CLUSTER_TIMEZONE_AMERICA_PUERTO_RICO"
	TIMEZONE_AMERICA_PUNTA_ARENAS           Timezone = "CLUSTER_TIMEZONE_AMERICA_PUNTA_ARENAS"
	TIMEZONE_AMERICA_RANKIN_INLET           Timezone = "CLUSTER_TIMEZONE_AMERICA_RANKIN_INLET"
	TIMEZONE_AMERICA_RECIFE                 Timezone = "CLUSTER_TIMEZONE_AMERICA_RECIFE"
	TIMEZONE_AMERICA_REGINA                 Timezone = "CLUSTER_TIMEZONE_AMERICA_REGINA"
	TIMEZONE_AMERICA_RESOLUTE               Timezone = "CLUSTER_TIMEZONE_AMERICA_RESOLUTE"
	TIMEZONE_AMERICA_RIO_BRANCO             Timezone = "CLUSTER_TIMEZONE_AMERICA_RIO_BRANCO"
	TIMEZONE_AMERICA_SANTAREM               Timezone = "CLUSTER_TIMEZONE_AMERICA_SANTAREM"
	TIMEZONE_AMERICA_SAO_PAULO              Timezone = "CLUSTER_TIMEZONE_AMERICA_SAO_PAULO"
	TIMEZONE_AMERICA_SCORESBYSUND           Timezone = "CLUSTER_TIMEZONE_AMERICA_SCORESBYSUND"
	TIMEZONE_AMERICA_SITKA                  Timezone = "CLUSTER_TIMEZONE_AMERICA_SITKA"
	TIMEZONE_AMERICA_SWIFT_CURRENT          Timezone = "CLUSTER_TIMEZONE_AMERICA_SWIFT_CURRENT"
	TIMEZONE_AMERICA_TEGUCIGALPA            Timezone = "CLUSTER_TIMEZONE_AMERICA_TEGUCIGALPA"
	TIMEZONE_AMERICA_THULE                  Timezone = "CLUSTER_TIMEZONE_AMERICA_THULE"
	TIMEZONE_AMERICA_TIJUANA                Timezone = "CLUSTER_TIMEZONE_AMERICA_TIJUANA"
	TIMEZONE_AMERICA_WHITEHORSE             Timezone = "CLUSTER_TIMEZONE_AMERICA_WHITEHORSE"
	TIMEZONE_AMERICA_WINNIPEG               Timezone = "CLUSTER_TIMEZONE_AMERICA_WINNIPEG"
	TIMEZONE_AMERICA_YAKUTAT                Timezone = "CLUSTER_TIMEZONE_AMERICA_YAKUTAT"

	// Antarctica timezones
	TIMEZONE_ANTARCTICA_CASEY     Timezone = "CLUSTER_TIMEZONE_ANTARCTICA_CASEY"
	TIMEZONE_ANTARCTICA_DAVIS     Timezone = "CLUSTER_TIMEZONE_ANTARCTICA_DAVIS"
	TIMEZONE_ANTARCTICA_MACQUARIE Timezone = "CLUSTER_TIMEZONE_ANTARCTICA_MACQUARIE"
	TIMEZONE_ANTARCTICA_MAWSON    Timezone = "CLUSTER_TIMEZONE_ANTARCTICA_MAWSON"
	TIMEZONE_ANTARCTICA_PALMER    Timezone = "CLUSTER_TIMEZONE_ANTARCTICA_PALMER"
	TIMEZONE_ANTARCTICA_ROTHERA   Timezone = "CLUSTER_TIMEZONE_ANTARCTICA_ROTHERA"
	TIMEZONE_ANTARCTICA_TROLL     Timezone = "CLUSTER_TIMEZONE_ANTARCTICA_TROLL"

	// Additional Asia timezones
	TIMEZONE_ASIA_ALMATY        Timezone = "CLUSTER_TIMEZONE_ASIA_ALMATY"
	TIMEZONE_ASIA_ANADYR        Timezone = "CLUSTER_TIMEZONE_ASIA_ANADYR"
	TIMEZONE_ASIA_AQTAU         Timezone = "CLUSTER_TIMEZONE_ASIA_AQTAU"
	TIMEZONE_ASIA_AQTOBE        Timezone = "CLUSTER_TIMEZONE_ASIA_AQTOBE"
	TIMEZONE_ASIA_ASHGABAT      Timezone = "CLUSTER_TIMEZONE_ASIA_ASHGABAT"
	TIMEZONE_ASIA_ATYRAU        Timezone = "CLUSTER_TIMEZONE_ASIA_ATYRAU"
	TIMEZONE_ASIA_BAGHDAD       Timezone = "CLUSTER_TIMEZONE_ASIA_BAGHDAD"
	TIMEZONE_ASIA_BAKU          Timezone = "CLUSTER_TIMEZONE_ASIA_BAKU"
	TIMEZONE_ASIA_BARNAUL       Timezone = "CLUSTER_TIMEZONE_ASIA_BARNAUL"
	TIMEZONE_ASIA_BISHKEK       Timezone = "CLUSTER_TIMEZONE_ASIA_BISHKEK"
	TIMEZONE_ASIA_CHITA         Timezone = "CLUSTER_TIMEZONE_ASIA_CHITA"
	TIMEZONE_ASIA_CHOIBALSAN    Timezone = "CLUSTER_TIMEZONE_ASIA_CHOIBALSAN"
	TIMEZONE_ASIA_COLOMBO       Timezone = "CLUSTER_TIMEZONE_ASIA_COLOMBO"
	TIMEZONE_ASIA_DAMASCUS      Timezone = "CLUSTER_TIMEZONE_ASIA_DAMASCUS"
	TIMEZONE_ASIA_DILI          Timezone = "CLUSTER_TIMEZONE_ASIA_DILI"
	TIMEZONE_ASIA_DUSHANBE      Timezone = "CLUSTER_TIMEZONE_ASIA_DUSHANBE"
	TIMEZONE_ASIA_FAMAGUSTA     Timezone = "CLUSTER_TIMEZONE_ASIA_FAMAGUSTA"
	TIMEZONE_ASIA_HO_CHI_MINH   Timezone = "CLUSTER_TIMEZONE_ASIA_HO_CHI_MINH"
	TIMEZONE_ASIA_HOVD          Timezone = "CLUSTER_TIMEZONE_ASIA_HOVD"
	TIMEZONE_ASIA_IRKUTSK       Timezone = "CLUSTER_TIMEZONE_ASIA_IRKUTSK"
	TIMEZONE_ASIA_JAKARTA       Timezone = "CLUSTER_TIMEZONE_ASIA_JAKARTA"
	TIMEZONE_ASIA_JAYAPURA      Timezone = "CLUSTER_TIMEZONE_ASIA_JAYAPURA"
	TIMEZONE_ASIA_JERUSALEM     Timezone = "CLUSTER_TIMEZONE_ASIA_JERUSALEM"
	TIMEZONE_ASIA_KABUL         Timezone = "CLUSTER_TIMEZONE_ASIA_KABUL"
	TIMEZONE_ASIA_KAMCHATKA     Timezone = "CLUSTER_TIMEZONE_ASIA_KAMCHATKA"
	TIMEZONE_ASIA_KHANDYGA      Timezone = "CLUSTER_TIMEZONE_ASIA_KHANDYGA"
	TIMEZONE_ASIA_KRASNOYARSK   Timezone = "CLUSTER_TIMEZONE_ASIA_KRASNOYARSK"
	TIMEZONE_ASIA_KUCHING       Timezone = "CLUSTER_TIMEZONE_ASIA_KUCHING"
	TIMEZONE_ASIA_MACAU         Timezone = "CLUSTER_TIMEZONE_ASIA_MACAU"
	TIMEZONE_ASIA_MAKASSAR      Timezone = "CLUSTER_TIMEZONE_ASIA_MAKASSAR"
	TIMEZONE_ASIA_MANILA        Timezone = "CLUSTER_TIMEZONE_ASIA_MANILA"
	TIMEZONE_ASIA_NICOSIA       Timezone = "CLUSTER_TIMEZONE_ASIA_NICOSIA"
	TIMEZONE_ASIA_NOVOKUZNETSK  Timezone = "CLUSTER_TIMEZONE_ASIA_NOVOKUZNETSK"
	TIMEZONE_ASIA_NOVOSIBIRSK   Timezone = "CLUSTER_TIMEZONE_ASIA_NOVOSIBIRSK"
	TIMEZONE_ASIA_OMSK          Timezone = "CLUSTER_TIMEZONE_ASIA_OMSK"
	TIMEZONE_ASIA_ORAL          Timezone = "CLUSTER_TIMEZONE_ASIA_ORAL"
	TIMEZONE_ASIA_PONTIANAK     Timezone = "CLUSTER_TIMEZONE_ASIA_PONTIANAK"
	TIMEZONE_ASIA_PYONGYANG     Timezone = "CLUSTER_TIMEZONE_ASIA_PYONGYANG"
	TIMEZONE_ASIA_QATAR         Timezone = "CLUSTER_TIMEZONE_ASIA_QATAR"
	TIMEZONE_ASIA_QOSTANAY      Timezone = "CLUSTER_TIMEZONE_ASIA_QOSTANAY"
	TIMEZONE_ASIA_QYZYLORDA     Timezone = "CLUSTER_TIMEZONE_ASIA_QYZYLORDA"
	TIMEZONE_ASIA_RIYADH        Timezone = "CLUSTER_TIMEZONE_ASIA_RIYADH"
	TIMEZONE_ASIA_SAKHALIN      Timezone = "CLUSTER_TIMEZONE_ASIA_SAKHALIN"
	TIMEZONE_ASIA_SAMARKAND     Timezone = "CLUSTER_TIMEZONE_ASIA_SAMARKAND"
	TIMEZONE_ASIA_SEOUL         Timezone = "CLUSTER_TIMEZONE_ASIA_SEOUL"
	TIMEZONE_ASIA_SHANGHAI      Timezone = "CLUSTER_TIMEZONE_ASIA_SHANGHAI"
	TIMEZONE_ASIA_SREDNEKOLYMSK Timezone = "CLUSTER_TIMEZONE_ASIA_SREDNEKOLYMSK"
	TIMEZONE_ASIA_TAIPEI        Timezone = "CLUSTER_TIMEZONE_ASIA_TAIPEI"
	TIMEZONE_ASIA_TASHKENT      Timezone = "CLUSTER_TIMEZONE_ASIA_TASHKENT"
	TIMEZONE_ASIA_TBILISI       Timezone = "CLUSTER_TIMEZONE_ASIA_TBILISI"
	TIMEZONE_ASIA_TEHRAN        Timezone = "CLUSTER_TIMEZONE_ASIA_TEHRAN"
	TIMEZONE_ASIA_THIMPHU       Timezone = "CLUSTER_TIMEZONE_ASIA_THIMPHU"
	TIMEZONE_ASIA_TOMSK         Timezone = "CLUSTER_TIMEZONE_ASIA_TOMSK"
	TIMEZONE_ASIA_ULAANBAATAR   Timezone = "CLUSTER_TIMEZONE_ASIA_ULAANBAATAR"
	TIMEZONE_ASIA_URUMQI        Timezone = "CLUSTER_TIMEZONE_ASIA_URUMQI"
	TIMEZONE_ASIA_VLADIVOSTOK   Timezone = "CLUSTER_TIMEZONE_ASIA_VLADIVOSTOK"
	TIMEZONE_ASIA_YAKUTSK       Timezone = "CLUSTER_TIMEZONE_ASIA_YAKUTSK"
	TIMEZONE_ASIA_YANGON        Timezone = "CLUSTER_TIMEZONE_ASIA_YANGON"
	TIMEZONE_ASIA_YEKATERINBURG Timezone = "CLUSTER_TIMEZONE_ASIA_YEKATERINBURG"
	TIMEZONE_ASIA_YEREVAN       Timezone = "CLUSTER_TIMEZONE_ASIA_YEREVAN"

	// Additional Atlantic timezones
	TIMEZONE_ATLANTIC_AZORES        Timezone = "CLUSTER_TIMEZONE_ATLANTIC_AZORES"
	TIMEZONE_ATLANTIC_BERMUDA       Timezone = "CLUSTER_TIMEZONE_ATLANTIC_BERMUDA"
	TIMEZONE_ATLANTIC_CANARY        Timezone = "CLUSTER_TIMEZONE_ATLANTIC_CANARY"
	TIMEZONE_ATLANTIC_FAROE         Timezone = "CLUSTER_TIMEZONE_ATLANTIC_FAROE"
	TIMEZONE_ATLANTIC_MADEIRA       Timezone = "CLUSTER_TIMEZONE_ATLANTIC_MADEIRA"
	TIMEZONE_ATLANTIC_SOUTH_GEORGIA Timezone = "CLUSTER_TIMEZONE_ATLANTIC_SOUTH_GEORGIA"
	TIMEZONE_ATLANTIC_STANLEY       Timezone = "CLUSTER_TIMEZONE_ATLANTIC_STANLEY"

	// Additional Australia timezones
	TIMEZONE_AUSTRALIA_BROKEN_HILL Timezone = "CLUSTER_TIMEZONE_AUSTRALIA_BROKEN_HILL"
	TIMEZONE_AUSTRALIA_DARWIN      Timezone = "CLUSTER_TIMEZONE_AUSTRALIA_DARWIN"
	TIMEZONE_AUSTRALIA_EUCLA       Timezone = "CLUSTER_TIMEZONE_AUSTRALIA_EUCLA"
	TIMEZONE_AUSTRALIA_HOBART      Timezone = "CLUSTER_TIMEZONE_AUSTRALIA_HOBART"
	TIMEZONE_AUSTRALIA_LINDEMAN    Timezone = "CLUSTER_TIMEZONE_AUSTRALIA_LINDEMAN"
	TIMEZONE_AUSTRALIA_LORD_HOWE   Timezone = "CLUSTER_TIMEZONE_AUSTRALIA_LORD_HOWE"
	TIMEZONE_AUSTRALIA_MELBOURNE   Timezone = "CLUSTER_TIMEZONE_AUSTRALIA_MELBOURNE"

	// Abbreviated timezones
	TIMEZONE_CET     Timezone = "CLUSTER_TIMEZONE_CET"
	TIMEZONE_CST6CDT Timezone = "CLUSTER_TIMEZONE_CST6CDT"
	TIMEZONE_EET     Timezone = "CLUSTER_TIMEZONE_EET"
	TIMEZONE_EST5EDT Timezone = "CLUSTER_TIMEZONE_EST5EDT"
	TIMEZONE_MET     Timezone = "CLUSTER_TIMEZONE_MET"
	TIMEZONE_MST7MDT Timezone = "CLUSTER_TIMEZONE_MST7MDT"
	TIMEZONE_PST8PDT Timezone = "CLUSTER_TIMEZONE_PST8PDT"
	TIMEZONE_WET     Timezone = "CLUSTER_TIMEZONE_WET"

	// Additional Europe timezones
	TIMEZONE_EUROPE_ANDORRA     Timezone = "CLUSTER_TIMEZONE_EUROPE_ANDORRA"
	TIMEZONE_EUROPE_ASTRAKHAN   Timezone = "CLUSTER_TIMEZONE_EUROPE_ASTRAKHAN"
	TIMEZONE_EUROPE_BELGRADE    Timezone = "CLUSTER_TIMEZONE_EUROPE_BELGRADE"
	TIMEZONE_EUROPE_BERLIN      Timezone = "CLUSTER_TIMEZONE_EUROPE_BERLIN"
	TIMEZONE_EUROPE_BRUSSELS    Timezone = "CLUSTER_TIMEZONE_EUROPE_BRUSSELS"
	TIMEZONE_EUROPE_BUCHAREST   Timezone = "CLUSTER_TIMEZONE_EUROPE_BUCHAREST"
	TIMEZONE_EUROPE_BUDAPEST    Timezone = "CLUSTER_TIMEZONE_EUROPE_BUDAPEST"
	TIMEZONE_EUROPE_CHISINAU    Timezone = "CLUSTER_TIMEZONE_EUROPE_CHISINAU"
	TIMEZONE_EUROPE_DUBLIN      Timezone = "CLUSTER_TIMEZONE_EUROPE_DUBLIN"
	TIMEZONE_EUROPE_GIBRALTAR   Timezone = "CLUSTER_TIMEZONE_EUROPE_GIBRALTAR"
	TIMEZONE_EUROPE_HELSINKI    Timezone = "CLUSTER_TIMEZONE_EUROPE_HELSINKI"
	TIMEZONE_EUROPE_ISTANBUL    Timezone = "CLUSTER_TIMEZONE_EUROPE_ISTANBUL"
	TIMEZONE_EUROPE_KALININGRAD Timezone = "CLUSTER_TIMEZONE_EUROPE_KALININGRAD"
	TIMEZONE_EUROPE_KIROV       Timezone = "CLUSTER_TIMEZONE_EUROPE_KIROV"
	TIMEZONE_EUROPE_KYIV        Timezone = "CLUSTER_TIMEZONE_EUROPE_KYIV"
	TIMEZONE_EUROPE_LISBON      Timezone = "CLUSTER_TIMEZONE_EUROPE_LISBON"
	TIMEZONE_EUROPE_MADRID      Timezone = "CLUSTER_TIMEZONE_EUROPE_MADRID"
	TIMEZONE_EUROPE_MALTA       Timezone = "CLUSTER_TIMEZONE_EUROPE_MALTA"
	TIMEZONE_EUROPE_MINSK       Timezone = "CLUSTER_TIMEZONE_EUROPE_MINSK"
	TIMEZONE_EUROPE_PARIS       Timezone = "CLUSTER_TIMEZONE_EUROPE_PARIS"
	TIMEZONE_EUROPE_PRAGUE      Timezone = "CLUSTER_TIMEZONE_EUROPE_PRAGUE"
	TIMEZONE_EUROPE_RIGA        Timezone = "CLUSTER_TIMEZONE_EUROPE_RIGA"
	TIMEZONE_EUROPE_ROME        Timezone = "CLUSTER_TIMEZONE_EUROPE_ROME"
	TIMEZONE_EUROPE_SAMARA      Timezone = "CLUSTER_TIMEZONE_EUROPE_SAMARA"
	TIMEZONE_EUROPE_SARATOV     Timezone = "CLUSTER_TIMEZONE_EUROPE_SARATOV"
	TIMEZONE_EUROPE_SIMFEROPOL  Timezone = "CLUSTER_TIMEZONE_EUROPE_SIMFEROPOL"
	TIMEZONE_EUROPE_SOFIA       Timezone = "CLUSTER_TIMEZONE_EUROPE_SOFIA"
	TIMEZONE_EUROPE_TALLINN     Timezone = "CLUSTER_TIMEZONE_EUROPE_TALLINN"
	TIMEZONE_EUROPE_TIRANE      Timezone = "CLUSTER_TIMEZONE_EUROPE_TIRANE"
	TIMEZONE_EUROPE_ULYANOVSK   Timezone = "CLUSTER_TIMEZONE_EUROPE_ULYANOVSK"
	TIMEZONE_EUROPE_VIENNA      Timezone = "CLUSTER_TIMEZONE_EUROPE_VIENNA"
	TIMEZONE_EUROPE_VILNIUS     Timezone = "CLUSTER_TIMEZONE_EUROPE_VILNIUS"
	TIMEZONE_EUROPE_VOLGOGRAD   Timezone = "CLUSTER_TIMEZONE_EUROPE_VOLGOGRAD"
	TIMEZONE_EUROPE_WARSAW      Timezone = "CLUSTER_TIMEZONE_EUROPE_WARSAW"
	TIMEZONE_EUROPE_ZURICH      Timezone = "CLUSTER_TIMEZONE_EUROPE_ZURICH"

	// Indian timezones
	TIMEZONE_INDIAN_CHAGOS    Timezone = "CLUSTER_TIMEZONE_INDIAN_CHAGOS"
	TIMEZONE_INDIAN_MALDIVES  Timezone = "CLUSTER_TIMEZONE_INDIAN_MALDIVES"
	TIMEZONE_INDIAN_MAURITIUS Timezone = "CLUSTER_TIMEZONE_INDIAN_MAURITIUS"

	// Additional Pacific timezones
	TIMEZONE_PACIFIC_APIA         Timezone = "CLUSTER_TIMEZONE_PACIFIC_APIA"
	TIMEZONE_PACIFIC_BOUGAINVILLE Timezone = "CLUSTER_TIMEZONE_PACIFIC_BOUGAINVILLE"
	TIMEZONE_PACIFIC_CHATHAM      Timezone = "CLUSTER_TIMEZONE_PACIFIC_CHATHAM"
	TIMEZONE_PACIFIC_EASTER       Timezone = "CLUSTER_TIMEZONE_PACIFIC_EASTER"
	TIMEZONE_PACIFIC_EFATE        Timezone = "CLUSTER_TIMEZONE_PACIFIC_EFATE"
	TIMEZONE_PACIFIC_FAKAOFO      Timezone = "CLUSTER_TIMEZONE_PACIFIC_FAKAOFO"
	TIMEZONE_PACIFIC_FIJI         Timezone = "CLUSTER_TIMEZONE_PACIFIC_FIJI"
	TIMEZONE_PACIFIC_GALAPAGOS    Timezone = "CLUSTER_TIMEZONE_PACIFIC_GALAPAGOS"
	TIMEZONE_PACIFIC_GAMBIER      Timezone = "CLUSTER_TIMEZONE_PACIFIC_GAMBIER"
	TIMEZONE_PACIFIC_GUADALCANAL  Timezone = "CLUSTER_TIMEZONE_PACIFIC_GUADALCANAL"
	TIMEZONE_PACIFIC_GUAM         Timezone = "CLUSTER_TIMEZONE_PACIFIC_GUAM"
	TIMEZONE_PACIFIC_KANTON       Timezone = "CLUSTER_TIMEZONE_PACIFIC_KANTON"
	TIMEZONE_PACIFIC_KIRITIMATI   Timezone = "CLUSTER_TIMEZONE_PACIFIC_KIRITIMATI"
	TIMEZONE_PACIFIC_KOSRAE       Timezone = "CLUSTER_TIMEZONE_PACIFIC_KOSRAE"
	TIMEZONE_PACIFIC_KWAJALEIN    Timezone = "CLUSTER_TIMEZONE_PACIFIC_KWAJALEIN"
	TIMEZONE_PACIFIC_MARQUESAS    Timezone = "CLUSTER_TIMEZONE_PACIFIC_MARQUESAS"
	TIMEZONE_PACIFIC_NAURU        Timezone = "CLUSTER_TIMEZONE_PACIFIC_NAURU"
	TIMEZONE_PACIFIC_NIUE         Timezone = "CLUSTER_TIMEZONE_PACIFIC_NIUE"
	TIMEZONE_PACIFIC_NORFOLK      Timezone = "CLUSTER_TIMEZONE_PACIFIC_NORFOLK"
	TIMEZONE_PACIFIC_NOUMEA       Timezone = "CLUSTER_TIMEZONE_PACIFIC_NOUMEA"
	TIMEZONE_PACIFIC_PAGO_PAGO    Timezone = "CLUSTER_TIMEZONE_PACIFIC_PAGO_PAGO"
	TIMEZONE_PACIFIC_PALAU        Timezone = "CLUSTER_TIMEZONE_PACIFIC_PALAU"
	TIMEZONE_PACIFIC_PITCAIRN     Timezone = "CLUSTER_TIMEZONE_PACIFIC_PITCAIRN"
	TIMEZONE_PACIFIC_PORT_MORESBY Timezone = "CLUSTER_TIMEZONE_PACIFIC_PORT_MORESBY"
	TIMEZONE_PACIFIC_RAROTONGA    Timezone = "CLUSTER_TIMEZONE_PACIFIC_RAROTONGA"
	TIMEZONE_PACIFIC_TAHITI       Timezone = "CLUSTER_TIMEZONE_PACIFIC_TAHITI"
	TIMEZONE_PACIFIC_TARAWA       Timezone = "CLUSTER_TIMEZONE_PACIFIC_TARAWA"
	TIMEZONE_PACIFIC_TONGATAPU    Timezone = "CLUSTER_TIMEZONE_PACIFIC_TONGATAPU"
)

// AllTimezones returns all valid timezones.
func AllTimezones() []Timezone {
	return []Timezone{
		TIMEZONE_UNSPECIFIED,
		TIMEZONE_AFRICA_JOHANNESBURG,
		TIMEZONE_AFRICA_LAGOS,
		TIMEZONE_AFRICA_NAIROBI,
		TIMEZONE_AMERICA_ANCHORAGE,
		TIMEZONE_AMERICA_ARAGUAINA,
		TIMEZONE_AMERICA_ATIKOKAN,
		TIMEZONE_AMERICA_BARBADOS,
		TIMEZONE_AMERICA_BOGOTA,
		TIMEZONE_AMERICA_CHICAGO,
		TIMEZONE_AMERICA_COSTA_RICA,
		TIMEZONE_AMERICA_DENVER,
		TIMEZONE_AMERICA_LOS_ANGELES,
		TIMEZONE_AMERICA_MEXICO_CITY,
		TIMEZONE_AMERICA_NEW_YORK,
		TIMEZONE_AMERICA_NORONHA,
		TIMEZONE_AMERICA_PANAMA,
		TIMEZONE_AMERICA_PHOENIX,
		TIMEZONE_AMERICA_SANTIAGO,
		TIMEZONE_AMERICA_ST_JOHNS,
		TIMEZONE_AMERICA_TORONTO,
		TIMEZONE_AMERICA_VANCOUVER,
		TIMEZONE_ASIA_BANGKOK,
		TIMEZONE_ASIA_DHAKA,
		TIMEZONE_ASIA_DUBAI,
		TIMEZONE_ASIA_HONG_KONG,
		TIMEZONE_ASIA_KARACHI,
		TIMEZONE_ASIA_KATHMANDU,
		TIMEZONE_ASIA_KOLKATA,
		TIMEZONE_ASIA_MAGADAN,
		TIMEZONE_ASIA_SINGAPORE,
		TIMEZONE_ASIA_TOKYO,
		TIMEZONE_ATLANTIC_CAPE_VERDE,
		TIMEZONE_AUSTRALIA_ADELAIDE,
		TIMEZONE_AUSTRALIA_BRISBANE,
		TIMEZONE_AUSTRALIA_PERTH,
		TIMEZONE_AUSTRALIA_SYDNEY,
		TIMEZONE_EUROPE_AMSTERDAM,
		TIMEZONE_EUROPE_ATHENS,
		TIMEZONE_EUROPE_LONDON,
		TIMEZONE_EUROPE_MOSCOW,
		TIMEZONE_PACIFIC_AUCKLAND,
		TIMEZONE_PACIFIC_HONOLULU,
		TIMEZONE_PACIFIC_MIDWAY,
		TIMEZONE_UTC,
		TIMEZONE_AFRICA_ABIDJAN,
		TIMEZONE_AFRICA_ALGIERS,
		TIMEZONE_AFRICA_BISSAU,
		TIMEZONE_AFRICA_CEUTA,
		TIMEZONE_AFRICA_MAPUTO,
		TIMEZONE_AFRICA_MONROVIA,
		TIMEZONE_AFRICA_NDJAMENA,
		TIMEZONE_AFRICA_SAO_TOME,
		TIMEZONE_AFRICA_TRIPOLI,
		TIMEZONE_AFRICA_TUNIS,
		TIMEZONE_AFRICA_WINDHOEK,
		TIMEZONE_AMERICA_ADAK,
		TIMEZONE_AMERICA_ARGENTINA_BUENOS_AIRES,
		TIMEZONE_AMERICA_ARGENTINA_CATAMARCA,
		TIMEZONE_AMERICA_ARGENTINA_CORDOBA,
		TIMEZONE_AMERICA_ARGENTINA_JUJUY,
		TIMEZONE_AMERICA_ARGENTINA_LA_RIOJA,
		TIMEZONE_AMERICA_ARGENTINA_MENDOZA,
		TIMEZONE_AMERICA_ARGENTINA_RIO_GALLEGOS,
		TIMEZONE_AMERICA_ARGENTINA_SALTA,
		TIMEZONE_AMERICA_ARGENTINA_SAN_JUAN,
		TIMEZONE_AMERICA_ARGENTINA_SAN_LUIS,
		TIMEZONE_AMERICA_ARGENTINA_TUCUMAN,
		TIMEZONE_AMERICA_ARGENTINA_USHUAIA,
		TIMEZONE_AMERICA_BAHIA,
		TIMEZONE_AMERICA_BELEM,
		TIMEZONE_AMERICA_BELIZE,
		TIMEZONE_AMERICA_BOA_VISTA,
		TIMEZONE_AMERICA_BOISE,
		TIMEZONE_AMERICA_CAMBRIDGE_BAY,
		TIMEZONE_AMERICA_CAMPO_GRANDE,
		TIMEZONE_AMERICA_CANCUN,
		TIMEZONE_AMERICA_CARACAS,
		TIMEZONE_AMERICA_CAYENNE,
		TIMEZONE_AMERICA_CHIHUAHUA,
		TIMEZONE_AMERICA_CIUDAD_JUAREZ,
		TIMEZONE_AMERICA_CUIABA,
		TIMEZONE_AMERICA_DANMARKSHAVN,
		TIMEZONE_AMERICA_DAWSON,
		TIMEZONE_AMERICA_DAWSON_CREEK,
		TIMEZONE_AMERICA_DETROIT,
		TIMEZONE_AMERICA_EDMONTON,
		TIMEZONE_AMERICA_EIRUNEPE,
		TIMEZONE_AMERICA_EL_SALVADOR,
		TIMEZONE_AMERICA_FORT_NELSON,
		TIMEZONE_AMERICA_FORTALEZA,
		TIMEZONE_AMERICA_GLACE_BAY,
		TIMEZONE_AMERICA_GOOSE_BAY,
		TIMEZONE_AMERICA_GRAND_TURK,
		TIMEZONE_AMERICA_GUATEMALA,
		TIMEZONE_AMERICA_GUAYAQUIL,
		TIMEZONE_AMERICA_GUYANA,
		TIMEZONE_AMERICA_HALIFAX,
		TIMEZONE_AMERICA_HAVANA,
		TIMEZONE_AMERICA_INDIANA_INDIANAPOLIS,
		TIMEZONE_AMERICA_INDIANA_KNOX,
		TIMEZONE_AMERICA_INDIANA_MARENGO,
		TIMEZONE_AMERICA_INDIANA_PETERSBURG,
		TIMEZONE_AMERICA_INDIANA_TELL_CITY,
		TIMEZONE_AMERICA_INDIANA_VEVAY,
		TIMEZONE_AMERICA_INDIANA_VINCENNES,
		TIMEZONE_AMERICA_INDIANA_WINAMAC,
		TIMEZONE_AMERICA_INUVIK,
		TIMEZONE_AMERICA_IQALUIT,
		TIMEZONE_AMERICA_JAMAICA,
		TIMEZONE_AMERICA_JUNEAU,
		TIMEZONE_AMERICA_KENTUCKY_LOUISVILLE,
		TIMEZONE_AMERICA_KENTUCKY_MONTICELLO,
		TIMEZONE_AMERICA_LA_PAZ,
		TIMEZONE_AMERICA_LIMA,
		TIMEZONE_AMERICA_MACEIO,
		TIMEZONE_AMERICA_MANAGUA,
		TIMEZONE_AMERICA_MANAUS,
		TIMEZONE_AMERICA_MARTINIQUE,
		TIMEZONE_AMERICA_MATAMOROS,
		TIMEZONE_AMERICA_MENOMINEE,
		TIMEZONE_AMERICA_MERIDA,
		TIMEZONE_AMERICA_METLAKATLA,
		TIMEZONE_AMERICA_MIQUELON,
		TIMEZONE_AMERICA_MONCTON,
		TIMEZONE_AMERICA_MONTERREY,
		TIMEZONE_AMERICA_MONTEVIDEO,
		TIMEZONE_AMERICA_NOME,
		TIMEZONE_AMERICA_NORTH_DAKOTA_BEULAH,
		TIMEZONE_AMERICA_NORTH_DAKOTA_CENTER,
		TIMEZONE_AMERICA_NORTH_DAKOTA_NEW_SALEM,
		TIMEZONE_AMERICA_OJINAGA,
		TIMEZONE_AMERICA_PARAMARIBO,
		TIMEZONE_AMERICA_PORTO_VELHO,
		TIMEZONE_AMERICA_PUERTO_RICO,
		TIMEZONE_AMERICA_PUNTA_ARENAS,
		TIMEZONE_AMERICA_RANKIN_INLET,
		TIMEZONE_AMERICA_RECIFE,
		TIMEZONE_AMERICA_REGINA,
		TIMEZONE_AMERICA_RESOLUTE,
		TIMEZONE_AMERICA_RIO_BRANCO,
		TIMEZONE_AMERICA_SANTAREM,
		TIMEZONE_AMERICA_SAO_PAULO,
		TIMEZONE_AMERICA_SCORESBYSUND,
		TIMEZONE_AMERICA_SITKA,
		TIMEZONE_AMERICA_SWIFT_CURRENT,
		TIMEZONE_AMERICA_TEGUCIGALPA,
		TIMEZONE_AMERICA_THULE,
		TIMEZONE_AMERICA_TIJUANA,
		TIMEZONE_AMERICA_WHITEHORSE,
		TIMEZONE_AMERICA_WINNIPEG,
		TIMEZONE_AMERICA_YAKUTAT,
		TIMEZONE_ANTARCTICA_CASEY,
		TIMEZONE_ANTARCTICA_DAVIS,
		TIMEZONE_ANTARCTICA_MACQUARIE,
		TIMEZONE_ANTARCTICA_MAWSON,
		TIMEZONE_ANTARCTICA_PALMER,
		TIMEZONE_ANTARCTICA_ROTHERA,
		TIMEZONE_ANTARCTICA_TROLL,
		TIMEZONE_ASIA_ALMATY,
		TIMEZONE_ASIA_ANADYR,
		TIMEZONE_ASIA_AQTAU,
		TIMEZONE_ASIA_AQTOBE,
		TIMEZONE_ASIA_ASHGABAT,
		TIMEZONE_ASIA_ATYRAU,
		TIMEZONE_ASIA_BAGHDAD,
		TIMEZONE_ASIA_BAKU,
		TIMEZONE_ASIA_BARNAUL,
		TIMEZONE_ASIA_BISHKEK,
		TIMEZONE_ASIA_CHITA,
		TIMEZONE_ASIA_CHOIBALSAN,
		TIMEZONE_ASIA_COLOMBO,
		TIMEZONE_ASIA_DAMASCUS,
		TIMEZONE_ASIA_DILI,
		TIMEZONE_ASIA_DUSHANBE,
		TIMEZONE_ASIA_FAMAGUSTA,
		TIMEZONE_ASIA_HO_CHI_MINH,
		TIMEZONE_ASIA_HOVD,
		TIMEZONE_ASIA_IRKUTSK,
		TIMEZONE_ASIA_JAKARTA,
		TIMEZONE_ASIA_JAYAPURA,
		TIMEZONE_ASIA_JERUSALEM,
		TIMEZONE_ASIA_KABUL,
		TIMEZONE_ASIA_KAMCHATKA,
		TIMEZONE_ASIA_KHANDYGA,
		TIMEZONE_ASIA_KRASNOYARSK,
		TIMEZONE_ASIA_KUCHING,
		TIMEZONE_ASIA_MACAU,
		TIMEZONE_ASIA_MAKASSAR,
		TIMEZONE_ASIA_MANILA,
		TIMEZONE_ASIA_NICOSIA,
		TIMEZONE_ASIA_NOVOKUZNETSK,
		TIMEZONE_ASIA_NOVOSIBIRSK,
		TIMEZONE_ASIA_OMSK,
		TIMEZONE_ASIA_ORAL,
		TIMEZONE_ASIA_PONTIANAK,
		TIMEZONE_ASIA_PYONGYANG,
		TIMEZONE_ASIA_QATAR,
		TIMEZONE_ASIA_QOSTANAY,
		TIMEZONE_ASIA_QYZYLORDA,
		TIMEZONE_ASIA_RIYADH,
		TIMEZONE_ASIA_SAKHALIN,
		TIMEZONE_ASIA_SAMARKAND,
		TIMEZONE_ASIA_SEOUL,
		TIMEZONE_ASIA_SHANGHAI,
		TIMEZONE_ASIA_SREDNEKOLYMSK,
		TIMEZONE_ASIA_TAIPEI,
		TIMEZONE_ASIA_TASHKENT,
		TIMEZONE_ASIA_TBILISI,
		TIMEZONE_ASIA_TEHRAN,
		TIMEZONE_ASIA_THIMPHU,
		TIMEZONE_ASIA_TOMSK,
		TIMEZONE_ASIA_ULAANBAATAR,
		TIMEZONE_ASIA_URUMQI,
		TIMEZONE_ASIA_VLADIVOSTOK,
		TIMEZONE_ASIA_YAKUTSK,
		TIMEZONE_ASIA_YANGON,
		TIMEZONE_ASIA_YEKATERINBURG,
		TIMEZONE_ASIA_YEREVAN,
		TIMEZONE_ATLANTIC_AZORES,
		TIMEZONE_ATLANTIC_BERMUDA,
		TIMEZONE_ATLANTIC_CANARY,
		TIMEZONE_ATLANTIC_FAROE,
		TIMEZONE_ATLANTIC_MADEIRA,
		TIMEZONE_ATLANTIC_SOUTH_GEORGIA,
		TIMEZONE_ATLANTIC_STANLEY,
		TIMEZONE_AUSTRALIA_BROKEN_HILL,
		TIMEZONE_AUSTRALIA_DARWIN,
		TIMEZONE_AUSTRALIA_EUCLA,
		TIMEZONE_AUSTRALIA_HOBART,
		TIMEZONE_AUSTRALIA_LINDEMAN,
		TIMEZONE_AUSTRALIA_LORD_HOWE,
		TIMEZONE_AUSTRALIA_MELBOURNE,
		TIMEZONE_CET,
		TIMEZONE_CST6CDT,
		TIMEZONE_EET,
		TIMEZONE_EST5EDT,
		TIMEZONE_MET,
		TIMEZONE_MST7MDT,
		TIMEZONE_PST8PDT,
		TIMEZONE_WET,
		TIMEZONE_EUROPE_ANDORRA,
		TIMEZONE_EUROPE_ASTRAKHAN,
		TIMEZONE_EUROPE_BELGRADE,
		TIMEZONE_EUROPE_BERLIN,
		TIMEZONE_EUROPE_BRUSSELS,
		TIMEZONE_EUROPE_BUCHAREST,
		TIMEZONE_EUROPE_BUDAPEST,
		TIMEZONE_EUROPE_CHISINAU,
		TIMEZONE_EUROPE_DUBLIN,
		TIMEZONE_EUROPE_GIBRALTAR,
		TIMEZONE_EUROPE_HELSINKI,
		TIMEZONE_EUROPE_ISTANBUL,
		TIMEZONE_EUROPE_KALININGRAD,
		TIMEZONE_EUROPE_KIROV,
		TIMEZONE_EUROPE_KYIV,
		TIMEZONE_EUROPE_LISBON,
		TIMEZONE_EUROPE_MADRID,
		TIMEZONE_EUROPE_MALTA,
		TIMEZONE_EUROPE_MINSK,
		TIMEZONE_EUROPE_PARIS,
		TIMEZONE_EUROPE_PRAGUE,
		TIMEZONE_EUROPE_RIGA,
		TIMEZONE_EUROPE_ROME,
		TIMEZONE_EUROPE_SAMARA,
		TIMEZONE_EUROPE_SARATOV,
		TIMEZONE_EUROPE_SIMFEROPOL,
		TIMEZONE_EUROPE_SOFIA,
		TIMEZONE_EUROPE_TALLINN,
		TIMEZONE_EUROPE_TIRANE,
		TIMEZONE_EUROPE_ULYANOVSK,
		TIMEZONE_EUROPE_VIENNA,
		TIMEZONE_EUROPE_VILNIUS,
		TIMEZONE_EUROPE_VOLGOGRAD,
		TIMEZONE_EUROPE_WARSAW,
		TIMEZONE_EUROPE_ZURICH,
		TIMEZONE_INDIAN_CHAGOS,
		TIMEZONE_INDIAN_MALDIVES,
		TIMEZONE_INDIAN_MAURITIUS,
		TIMEZONE_PACIFIC_APIA,
		TIMEZONE_PACIFIC_BOUGAINVILLE,
		TIMEZONE_PACIFIC_CHATHAM,
		TIMEZONE_PACIFIC_EASTER,
		TIMEZONE_PACIFIC_EFATE,
		TIMEZONE_PACIFIC_FAKAOFO,
		TIMEZONE_PACIFIC_FIJI,
		TIMEZONE_PACIFIC_GALAPAGOS,
		TIMEZONE_PACIFIC_GAMBIER,
		TIMEZONE_PACIFIC_GUADALCANAL,
		TIMEZONE_PACIFIC_GUAM,
		TIMEZONE_PACIFIC_KANTON,
		TIMEZONE_PACIFIC_KIRITIMATI,
		TIMEZONE_PACIFIC_KOSRAE,
		TIMEZONE_PACIFIC_KWAJALEIN,
		TIMEZONE_PACIFIC_MARQUESAS,
		TIMEZONE_PACIFIC_NAURU,
		TIMEZONE_PACIFIC_NIUE,
		TIMEZONE_PACIFIC_NORFOLK,
		TIMEZONE_PACIFIC_NOUMEA,
		TIMEZONE_PACIFIC_PAGO_PAGO,
		TIMEZONE_PACIFIC_PALAU,
		TIMEZONE_PACIFIC_PITCAIRN,
		TIMEZONE_PACIFIC_PORT_MORESBY,
		TIMEZONE_PACIFIC_RAROTONGA,
		TIMEZONE_PACIFIC_TAHITI,
		TIMEZONE_PACIFIC_TARAWA,
		TIMEZONE_PACIFIC_TONGATAPU,
	}
}

// TimezoneToFriendlyName returns a friendly name for the timezone.
func TimezoneToFriendlyName(timezone Timezone) string {
	// its not possible to use TIMEZONE_UNSPECIFIED as a timezone, so return an empty string
	if timezone == TIMEZONE_UNSPECIFIED {
		return ""
	}

	// Strip the CLUSTER_TIMEZONE_ prefix
	name := strings.TrimPrefix(string(timezone), "CLUSTER_TIMEZONE_")

	// Replace only the first underscore (region separator) with a slash
	return strings.Replace(name, "_", "/", 1)
}

// AllTimezonesAsStrings returns all valid timezones as a slice of strings.
func AllTimezonesAsStrings() []string {
	timezones := AllTimezones()
	result := make([]string, len(timezones))
	for i, tz := range timezones {
		result[i] = string(tz)
	}
	return result
}

// ParseTimezone validates and converts a string to a Timezone type.
// It returns the Timezone and true if the string is a valid timezone,
// or an empty Timezone and false if it is not valid.
func ParseTimezone(s string) (Timezone, bool) {
	for _, tz := range AllTimezones() {
		if string(tz) == s {
			return tz, true
		}
	}
	return Timezone(s), false
}

// IsValidTimezone checks if the given string is a valid timezone.
func IsValidTimezone(s string) bool {
	_, ok := ParseTimezone(s)
	return ok
}
