// Code generated by queries_gen.go DO NOT EDIT.

// MIT License
//
// Copyright (c) 2021 Rubrik
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

package cluster

// allClusterGlobalSlas GraphQL query
var allClusterGlobalSlasQuery = `query SdkGolangAllClusterGlobalSlas($clusterUuid: UUID!) {
  result: allClusterGlobalSlas(cdmClusterUUID: $clusterUuid) {
    id
    name
  }
}`

// allClustersConnection GraphQL query
var allClustersConnectionQuery = `query SdkGolangAllClustersConnection(
  $first: Int
  $after: String
  $filter: ClusterFilterInput
  $sortBy: ClusterSortByEnum
  $sortOrder: SortOrder
) {
  result: allClusterConnection(
    filter: $filter
    sortBy: $sortBy
    sortOrder: $sortOrder
    first: $first
    after: $after
  ) {
    edges {
      cursor
      node {
        id
        name
        ccprovisionInfo {
          progress
          jobStatus
          jobType
          vendor
        }
        cloudInfo {
          name
          region
          regionId
          networkName
          nativeCloudAccountName
          vendor
          nativeCloudAccountId
          cloudAccount
          storageConfig {
            locationName
            locationId
            isImmutable
            isUsingManagedIdentity
          }
        }
        clusterNodeConnection {
          edges {
            node {
              brikId
              ipAddress
              needsInspection
              cpuCores
              ram
              clusterId
              networkSpeed
              hostname
              id
            }
          }
        }
        productType
        type
        status
        systemStatus
        timezone
        version
      }
    }
    pageInfo {
      startCursor
      endCursor
      hasNextPage
      hasPreviousPage
    }
    count
  }
}`

// canIgnoreClusterRemovalPrechecks GraphQL query
var canIgnoreClusterRemovalPrechecksQuery = `query SdkGolangCanIgnoreClusterRemovalPrechecks($clusterUuid: UUID!) {
  result: canIgnoreClusterRemovalPrechecks(clusterUuid: $clusterUuid) {
    isDisconnected
    ignorePrecheckTime
    lastConnectionTime
    canIgnorePrecheck
    isAirGapped
  }
}`

// cdmReleaseDetailsForClusterFromSupportPortal GraphQL query
var cdmReleaseDetailsForClusterFromSupportPortalQuery = `query SdkGolangCdmReleaseDetailsForClusterFromSupportPortal(
  $listClusterUuid: [UUID!]!
  $filterVersion: String!
  $fetchLinks: Boolean!
  $filterUpgradeable: Boolean!
  $shouldShowAll: Boolean!
  $filterAfterSource: Boolean!
  $sortOrder: SortOrder
) {
  result: getCdmReleaseDetailsForClusterFromSupportPortal(
    listClusterUuid: $listClusterUuid
    filterVersion: $filterVersion
    fetchLinks: $fetchLinks
    filterUpgradeable: $filterUpgradeable
    shouldShowAll: $shouldShowAll
    filterAfterSource: $filterAfterSource
    sortOrder: $sortOrder
  ) {
    releaseDetails {
      name
      isRecommended
      isUpgradable
      md5Sum
      size
      tarDownloadLink
    }
  }
}`

// clusterDnsServers GraphQL query
var clusterDnsServersQuery = `query SdkGolangClusterDnsServers($clusterUuid: UUID!) {
  result: clusterDns(clusterUuid: $clusterUuid) {
    servers
    domains
  }
}`

// clusterNtpServers GraphQL query
var clusterNtpServersQuery = `query SdkGolangClusterNtpServers($id: String!) {
  result: clusterNtpServers(input: { id: $id }) {
    data {
      server
      symmetricKey {
        key
        keyId
        keyType
      }
    }
  }
}`

// clusterRcvLocations GraphQL query
var clusterRcvLocationsQuery = `query SdkGolangClusterRcvLocations(
  $clusterUuid: UUID!
  $first: Int
  $after: String
  $last: Int
  $before: String
  $sortOrder: SortOrder
) {
  result: clusterRcvLocations(
    cdmClusterUUID: $clusterUuid
    first: $first
    after: $after
    last: $last
    before: $before
    sortOrder: $sortOrder
  ) {
    edges {
      cursor
      node {
        id
        name
      }
    }
  }
}`

// clusterSettings GraphQL query
var clusterSettingsQuery = `query SdkGolangClusterSettings($id: UUID!) {
  result: cluster(clusterUuid: $id) {
    id
    name
    version
    status
    timezone
    rawAddress
    geoLocation {
      address
    }
    ipmiInfo {
      isAvailable
      usesHttps
      usesIkvm
    }
  }
}`

// clusterWithUpgradesInfo GraphQL query
var clusterWithUpgradesInfoQuery = `query SdkGolangClusterWithUpgradesInfo(
  $first: Int
  $after: String
  $last: Int
  $before: String
  $sortOrder: SortOrder
  $sortBy: UpgradeInfoSortByEnum
  $clusterLocation: [String!]
  $connectionState: [ClusterStatus!]
  $downloadedVersion: [String!]
  $eosStatus: [ClusterEosStatus!]
  $id: [UUID!]
  $installedVersion: [String!]
  $minSoftwareVersion: String
  $name: [String!]
  $prechecksStatus: [PrechecksStatusTypeEnum!]
  $productType: [ClusterProductEnum!]
  $registrationTimeGt: DateTime
  $registrationTimeLt: DateTime
  $type: [ClusterTypeEnum!]
  $upgradeJobStatus: [ClusterJobStatusTypeEnum!]
  $upgradeScheduled: Boolean
  $upgradeStatusCategory: [String!]
  $versionStatus: [VersionStatus!]
) {
  result: clusterWithUpgradesInfo(
    first: $first
    after: $after
    last: $last
    before: $before
    sortOrder: $sortOrder
    sortBy: $sortBy
    upgradeFilter: {
      clusterLocation: $clusterLocation
      connectionState: $connectionState
      downloadedVersion: $downloadedVersion
      eosStatus: $eosStatus
      id: $id
      installedVersion: $installedVersion
      minSoftwareVersion: $minSoftwareVersion
      name: $name
      prechecksStatus: $prechecksStatus
      productType: $productType
      registrationTime_gt: $registrationTimeGt
      registrationTime_lt: $registrationTimeLt
      type: $type
      upgradeJobStatus: $upgradeJobStatus
      upgradeScheduled: $upgradeScheduled
      upgradeStatusCategory: $upgradeStatusCategory
      versionStatus: $versionStatus
    }
  ) {
    edges {
      cursor
      node {
        id
        name
        cdmUpgradeInfo {
          clusterUuid
          version
          versionStatus
          clusterJobStatus
          clusterStatus {
            message
            status
            statusInfo {
              completedNodes
              currentNode
            }
          }
          currentStateProgress
          downloadedVersion
          fastUpgradePreferred
          finishedStates
          isRuSupported
          overallProgress
          pendingStates
          previousVersion
          ruUnsupportabilityReason
          scheduleUpgradeAction
          scheduleUpgradeAt
          scheduleUpgradeMode
          stateMachineStatus
          stateMachineStatusAt
          upgradeEndAt
          upgradeEventSeriesId
          upgradeStartAt
          upgradeStatusV2 {
            rscClusterUpgradeStatus
            uiStatus
            uiStatusAttributes {
              sourceVersion
              targetVersion
              progress
              errorMsg
              upgradeMode
            }
          }
          upgradeRecommendationInfo {
            recommendation
            nextReleaseRecommendation
            upgradability
          }
          lastUpgradeDuration {
            clusterUuid
            fastUpgradeDuration
            rollingUpgradeDuration
          }
        }
      }
    }
    pageInfo {
      startCursor
      endCursor
      hasPreviousPage
      hasNextPage
    }
    count
  }
}`

// multiHopUpgradePath GraphQL query
var multiHopUpgradePathQuery = `query SdkGolangMultiHopUpgradePath(
  $clusterUuid: UUID!
  $sourceVersion: String
  $targetVersion: String!
  $shouldIncludeFullVersionName: Boolean
) {
  result: multiHopUpgradePath(
    clusterUuid: $clusterUuid
    sourceVersion: $sourceVersion
    targetVersion: $targetVersion
    shouldIncludeFullVersionName: $shouldIncludeFullVersionName
  ) {
    versionPath
  }
}`

// removeCdmCluster GraphQL query
var removeCdmClusterQuery = `mutation SdkGolangRemoveCdmCluster($clusterUuid: UUID!, $expireInDays: Long, $isForce: Boolean!) {
  result: removeCdmCluster(
    clusterUUID: $clusterUuid
    expireInDays: $expireInDays
    isForce: $isForce
  )
}`

// selfServeRollingUpgrade GraphQL query
var selfServeRollingUpgradeQuery = `query SdkGolangSelfServeRollingUpgrade {
  result: selfServeRollingUpgrade {
    enabled
  }
}`

// setSelfServeRollingUpgrade GraphQL query
var setSelfServeRollingUpgradeQuery = `mutation SdkGolangSetSelfServeRollingUpgrade($enabled: Boolean!) {
  result: setSelfServeRollingUpgrade(input: {
    enabled: $enabled,
  }) {
    enabled
  }
}`

// slaSourceClusters GraphQL query
var slaSourceClustersQuery = `query SdkGolangSlaSourceClusters(
  $after: String
  $first: Int
  $sortBy: SlaSourceClustersSortByField
  $sortOrder: SortOrder
  $filter: [SlaSourceClustersFilter!]
  $isArchivalSelected: Boolean
  $selectedReplication: SlaReplicationConfiguration
  $slaId: UUID
) {
  result: slaSourceClusters(
    after: $after
    first: $first
    sortBy: $sortBy
    sortOrder: $sortOrder
    filter: $filter
    isArchivalSelected: $isArchivalSelected
    selectedReplication: $selectedReplication
    slaId: $slaId
  ) {
    edges {
      cursor
      node {
        disableReasons
        hasProtectedObjects
        cluster {
          id
          name
          version
          clusterInfo {
            ... on LocalClusterInfo {
              isConnected
            }
            ... on CrossAccountClusterInfo {
              isConnected
            }
          }
        }
      }
    }
    pageInfo {
      startCursor
      endCursor
      hasPreviousPage
      hasNextPage
    }
    count
  }
}`

// updateClusterNtpServers GraphQL query
var updateClusterNtpServersQuery = `mutation SdkGolangUpdateClusterNtpServers($input: UpdateClusterNtpServersInput!) {
  result: updateClusterNtpServers(input: $input) {
    success
  }
}`

// updateClusterSettings GraphQL query
var updateClusterSettingsQuery = `mutation SdkGolangUpdateClusterSettings(
  $clusterID: UUID!
  $address: String!
  $name: String
  $timezone: ClusterTimezoneType!
) {
  result: updateClusterSettings(
    input: {
      clusterUuid: $clusterID
      id: "me"
      clusterUpdate: {
        geolocation: { address: $address }
        name: $name
        timezone: { timezone: $timezone }
      }
    }
  ) {
    geolocation {
      address
    }
    clusterUuid
    name
    timezone {
      timezone
    }
  }
}`

// updateCusterDnsAndSearchDomains GraphQL query
var updateCusterDnsAndSearchDomainsQuery = `mutation SdkGolangUpdateCusterDnsAndSearchDomains(
  $domains: [String!]!
  $id: String!
  $servers: [String!]!
) {
  result: updateDnsServersAndSearchDomains(
    input: { domains: $domains, id: $id, servers: $servers }
  ) {
    success
  }
}`

// verifySlaWithReplicationToCluster GraphQL query
var verifySlaWithReplicationToClusterQuery = `query SdkGolangVerifySlaWithReplicationToCluster($clusterUuid: UUID!, $includeArchived: Boolean!) {
  result: verifySlaWithReplicationToCluster(
    cdmClusterUUID: $clusterUuid
    includeArchived: $includeArchived
  ) {
    isActiveSla
  }
}`
