// Code generated by queries_gen.go DO NOT EDIT.

// MIT License
//
// Copyright (c) 2021 Rubrik
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

package devops

// addAzureDevopsCloudAccountWithoutOauth GraphQL query
var addAzureDevopsCloudAccountWithoutOauthQuery = `mutation SdkGolangAddAzureDevopsCloudAccountWithoutOauth(
  $organizationNativeIds:         [String!],
  $tenantId:                      String!,
  $cloudType:                     AzureCloudType!,
  $featuresWithPermissionsGroups: [FeatureWithPermissionsGroups!]!,
  $hostType:                      DevopsHostType,
  $storageType:                   DevOpsStorageType,
  $backupLocationId:              UUID,
  $exocomputeCloudAccountId:      UUID,
  $exocomputeRegion:              String,
) {
  result: addAzureDevOpsCloudAccountWithoutOauth(input: {
    organizationNativeIds:         $organizationNativeIds,
    tenantId:                      $tenantId,
    cloudType:                     $cloudType,
    featuresWithPermissionsGroups: $featuresWithPermissionsGroups,
    hostType:                      $hostType,
    storageType:                   $storageType,
    backupLocationId:              $backupLocationId,
    exocomputeCloudAccountId:      $exocomputeCloudAccountId,
    exocomputeRegion:              $exocomputeRegion,
  })
}`

// azureDevopsOrganization GraphQL query
var azureDevopsOrganizationQuery = `query SdkGolangAzureDevopsOrganization($workloadId: UUID!) {
  result: azureDevOpsOrganization(workloadId: $workloadId) {
    id
    nativeId
    tenantId
    tenantUuid
    connectionStatus
    authenticationMechanism
    clientId
    repoHostType
    devOpsOrgType
    projectCount
    repoCount
    lastRefreshTime
    name
    objectType
    backupLocation {
      id
      archivalGroupId
      name
      storageType
      cloudSpecificRegion {
        azureRegion
      }
    }
    cloudNativeExocompute {
      id
      hostName
      region {
        region {
          azureRegion
        }
      }
    }
    rubrikHostedExocompute {
      region
    }
  }
}`

// azureDevopsOrganizations GraphQL query
var azureDevopsOrganizationsQuery = `query SdkGolangAzureDevopsOrganizations(
  $first:      Int,
  $after:      String,
  $queryType:  QueryType!,
  $ancestorId: String!,
  $filter:     [Filter!]!,
) {
  result: azureDevOpsOrganizations(
    first:      $first,
    after:      $after,
    queryType:  $queryType,
    ancestorId: $ancestorId,
    filter:     $filter,
  ) {
    nodes {
      id
      nativeId
      tenantId
      tenantUuid
      connectionStatus
      authenticationMechanism
      clientId
      repoHostType
      devOpsOrgType
      projectCount
      repoCount
      lastRefreshTime
      name
      objectType
      backupLocation {
        id
        archivalGroupId
        name
        storageType
        cloudSpecificRegion {
          azureRegion
        }
      }
      cloudNativeExocompute {
        id
        hostName
        region {
          region {
            azureRegion
          }
        }
      }
      rubrikHostedExocompute {
        region
      }
    }
    pageInfo {
      endCursor
      hasNextPage
    }
    count
  }
}`

// azureDevopsProject GraphQL query
var azureDevopsProjectQuery = `query SdkGolangAzureDevopsProject($workloadId: UUID!) {
  result: azureDevOpsProject(workloadId: $workloadId) {
    id
    nativeId
    name
    orgId
    orgName
    url
    repoCount
    objectType
  }
}`

// azureDevopsProjects GraphQL query
var azureDevopsProjectsQuery = `query SdkGolangAzureDevopsProjects(
  $first:      Int,
  $after:      String,
  $queryType:  QueryType!,
  $ancestorId: String!,
  $filter:     [Filter!]!,
) {
  result: azureDevOpsProjects(
    first:      $first,
    after:      $after,
    queryType:  $queryType,
    ancestorId: $ancestorId,
    filter:     $filter,
  ) {
    nodes {
      id
      nativeId
      name
      orgId
      orgName
      url
      repoCount
      objectType
    }
    pageInfo {
      endCursor
      hasNextPage
    }
    count
  }
}`

// azureDevopsRepositories GraphQL query
var azureDevopsRepositoriesQuery = `query SdkGolangAzureDevopsRepositories(
  $first:      Int,
  $after:      String,
  $queryType:  QueryType!,
  $ancestorId: String!,
  $filter:     [Filter!]!,
) {
  result: azureDevOpsRepositories(
    first:      $first,
    after:      $after,
    queryType:  $queryType,
    ancestorId: $ancestorId,
    filter:     $filter,
  ) {
    nodes {
      id
      name
      orgId
      orgName
      projectId
      projectName
      url
      size
      objectType
    }
    pageInfo {
      endCursor
      hasNextPage
    }
    count
  }
}`

// azureDevopsRepository GraphQL query
var azureDevopsRepositoryQuery = `query SdkGolangAzureDevopsRepository($workloadId: UUID!) {
  result: azureDevOpsRepository(workloadId: $workloadId) {
    id
    name
    orgId
    orgName
    projectId
    projectName
    url
    size
    objectType
  }
}`

// deleteAzureDevopsCloudAccountWithoutOauth GraphQL query
var deleteAzureDevopsCloudAccountWithoutOauthQuery = `mutation SdkGolangDeleteAzureDevopsCloudAccountWithoutOauth(
  $organizationId:  UUID!,
  $deleteSnapshots: Boolean,
) {
  result: deleteAzureDevOpsCloudAccountWithoutOauth(input: {
    organizationId:  $organizationId,
    deleteSnapshots: $deleteSnapshots,
  })
}`

// devopsCloudAccountListLatestPermissions GraphQL query
var devopsCloudAccountListLatestPermissionsQuery = `query SdkGolangDevopsCloudAccountListLatestPermissions($featuresWithPermissionsGroups: [FeatureWithPermissionsGroups!]) {
  result: devOpsCloudAccountListLatestPermissions(input: {
    featuresWithPermissionsGroups: $featuresWithPermissionsGroups,
  }) {
    featurePermissions {
      feature
      permissionJson
      version
      permissionsGroupVersions {
        permissionsGroup
        version
      }
    }
    groupPermissions {
      group
      permissions
      version
    }
  }
}`

// generateAzureDevopsOnboardingScript GraphQL query
var generateAzureDevopsOnboardingScriptQuery = `query SdkGolangGenerateAzureDevopsOnboardingScript(
  $tenantId:                      String!,
  $cloudType:                     AzureCloudType!,
  $featuresWithPermissionsGroups: [FeatureWithPermissionsGroups!]!,
  $organizationNativeIds:         [String!],
) {
  result: generateAzureDevOpsOnboardingScript(input: {
    tenantId:                      $tenantId,
    cloudType:                     $cloudType,
    featuresWithPermissionsGroups: $featuresWithPermissionsGroups,
    organizationNativeIds:         $organizationNativeIds,
  }) {
    bashScript
    powershellScript
  }
}`

// updateAzureDevopsCloudAccount GraphQL query
var updateAzureDevopsCloudAccountQuery = `mutation SdkGolangUpdateAzureDevopsCloudAccount(
  $organizationId:           UUID!,
  $backupLocationId:         UUID,
  $backupRegion:             String,
  $exocomputeCloudAccountId: UUID,
  $hostType:                 DevopsHostType,
  $storageType:              DevOpsStorageType,
  $exocomputeRegion:         String,
) {
  result: updateAzureDevOpsCloudAccount(input: {
    organizationId:           $organizationId,
    backupLocationId:         $backupLocationId,
    backupRegion:             $backupRegion,
    exocomputeCloudAccountId: $exocomputeCloudAccountId,
    hostType:                 $hostType,
    storageType:              $storageType,
    exocomputeRegion:         $exocomputeRegion,
  })
}`

// upgradeAzureDevopsCloudAccountWithoutOauth GraphQL query
var upgradeAzureDevopsCloudAccountWithoutOauthQuery = `mutation SdkGolangUpgradeAzureDevopsCloudAccountWithoutOauth($organizationId: UUID!, $featuresToUpgrade: [FeatureWithPermissionsGroups!]!) {
  result: upgradeAzureDevOpsCloudAccountWithoutOauth(input: {
    organizationId:    $organizationId,
    featuresToUpgrade: $featuresToUpgrade,
  }) {
    errorMessage
  }
}`
