// Code generated by queries_gen.go DO NOT EDIT.

// MIT License
//
// Copyright (c) 2021 Rubrik
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

package tags

// cloudNativeCustomerTags GraphQL query
var cloudNativeCustomerTagsQuery = `query SdkGolangCloudNativeCustomerTags($cloudVendor: CloudVendor!, $cloudAccountId: UUID) {
    result: cloudNativeCustomerTags(cloudVendor: $cloudVendor, cloudAccountId: $cloudAccountId) {
        customerTags {
            key
            value
        }
        shouldOverrideResourceTags
    }
}`

// setCustomerTags GraphQL query
var setCustomerTagsQuery = `mutation SdkGolangSetCustomerTags($cloudVendor: CloudVendor!, $customerTags: [TagInput!]!, $shouldOverrideResourceTags: Boolean!) {
    result: setCustomerTags(input: {
        cloudVendor: $cloudVendor
        customerTags: {
            tagList: $customerTags
        }
        shouldOverrideResourceTags: $shouldOverrideResourceTags
    })
}`
