// Code generated by queries_gen.go DO NOT EDIT.

// MIT License
//
// Copyright (c) 2021 Rubrik
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

package kubernetes

// activitySeries GraphQL query
var activitySeriesQuery = `query SdkGolangActivitySeries($input: ActivitySeriesInput!, $after: String) {
    activitySeries(input: $input) {
        activityConnection(after: $after) {
            nodes {
                activityInfo
                message
                status
                time
                severity
            }
            pageInfo {
                endCursor
                hasNextPage
            }
            count
        }
    }
}`

// addK8sCluster GraphQL query
var addK8sClusterQuery = `mutation SdkGolangAddK8sCluster(
    $clusterUuid: String!,
    $config: K8sClusterCreateInput!) {
    result: addK8sCluster(
        input: {
            clusterUuid: $clusterUuid,
            config: $config
        }
    ) {
        id
        name
        registry
        distribution
        kuprServerProxyConfig {
            cert
            ipAddress
            port
        }
        transport
        lastRefreshTime
        region
        onboardingType
        status
    }
}`

// addK8sProtectionSet GraphQL query
var addK8sProtectionSetQuery = `mutation SdkGolangAddK8sProtectionSet($config: K8sProtectionSetAddInput!) {
    result: addK8sProtectionSet(input: {config: $config}) {
        id
        definition
        hookConfigs
        kubernetesClusterUuid
        kubernetesNamespace
        name
        rsType
    }
}`

// createK8sProtectionSetSnapshot GraphQL query
var createK8sProtectionSetSnapshotQuery = `mutation SdkGolangCreateK8sProtectionSetSnapshot(
    $protectionSetId: String!,
    $jobConfig: BaseOnDemandSnapshotConfigInput!) {
    result: createK8sProtectionSetSnapshot(
        input: {
            protectionSetId: $protectionSetId,
            jobConfig: $jobConfig
        }
    ) {
        status
        startTime
        progress
        nodeId
        links {
            rel
            href
        }
        id
        error {
            message
        }
        endTime
    }
}`

// deleteK8sProtectionSet GraphQL query
var deleteK8sProtectionSetQuery = `mutation SdkGolangDeleteK8sProtectionSet($id: UUID!, $preserveSnapshots: Boolean!) {
    result: deleteK8sProtectionSet(input: {id: $id, preserveSnapshots: $preserveSnapshots}) {
        success
    }
}`

// exportK8sProtectionSetSnapshot GraphQL query
var exportK8sProtectionSetSnapshotQuery = `mutation SdkGolangExportK8sProtectionSetSnapshot(
    $id: String!,
    $jobConfig: ExportK8sProtectionSetSnapshotJobConfigInput!) {
    result: exportK8sProtectionSetSnapshot(
        input: {
            id: $id,
            jobConfig: $jobConfig
        }
    ) {
        status
        startTime
        progress
        nodeId
        links {
            rel
            href
        }
        id
        error {
            message
        }
        endTime
    }
}`

// getProtectionSetSnapshot GraphQL query
var getProtectionSetSnapshotQuery = `query SdkGolangGetProtectionSetSnapshot($fid: UUID!) {
    result: k8sProtectionSetSnapshots(
        k8sProtectionSetFid: $fid,
        first: 1,
        sortOrder: DESC
    ) {
        data {
            baseSnapshotSummary {
                id
                slaId
            }
        }
    }
}`

// k8sJobInstance GraphQL query
var k8sJobInstanceQuery = `query SdkGolangK8sJobInstance($k8sJobId: String!, $clusterUuid: UUID!) {
    result: k8sJobInstance(k8sJobId: $k8sJobId, clusterUuid: $clusterUuid) {
        id
        eventSeriesId
        startTime
        endTime
        jobStatus
    }
}`

// k8sObjectFidByType GraphQL query
var k8sObjectFidByTypeQuery = `query SdkGolangK8sObjectFidByType($k8SObjectInternalIdArg: UUID!, $clusterUuid: UUID!, $kubernetesObjectType: KubernetesObjectType!) {
    result: k8sObjectFidByType(k8SObjectInternalIdArg: $k8SObjectInternalIdArg, clusterUuid: $clusterUuid, kubernetesObjectType: $kubernetesObjectType)
}`

// k8sObjectInternalIdByType GraphQL query
var k8sObjectInternalIdByTypeQuery = `query SdkGolangK8sObjectInternalIdByType($fid: UUID!, $clusterUuid: UUID!, $kubernetesObjectType: KubernetesObjectType!) {
    result: k8sObjectInternalIdByType(fid: $fid, clusterUuid: $clusterUuid, kubernetesObjectType: $kubernetesObjectType)
}`

// k8sProtectionSet GraphQL query
var k8sProtectionSetQuery = `query SdkGolangK8sProtectionSet($fid: UUID!) {
    result: kubernetesProtectionSet(fid: $fid) {
        cdmId
        clusterUuid
        configuredSlaDomain {
            id
            name
        }
        effectiveRetentionSlaDomain {
            id
            name
        }
        effectiveSlaDomain {
            id
            name
        }
        effectiveSlaSourceObject {
            fid
            name
            objectType
        }
        id
        isRelic
        k8sClusterUuid
        Name
        namespace
        objectType
        pendingSla {
            id
            name
        }
        primaryClusterLocation {
            clusterUuid
            createDate
            id
            isActive
            isArchived
            name
            type
        }
        primaryClusterUuid
        replicatedObjectCount
        rsName
        rsType
        slaAssignment
        slaPauseStatus
    }
}`

// restoreK8sProtectionSetSnapshot GraphQL query
var restoreK8sProtectionSetSnapshotQuery = `mutation SdkGolangRestoreK8sProtectionSetSnapshot(
    $id: String!,
    $jobConfig: RestoreK8sProtectionSetSnapshotJobConfigInput!) {
    result: restoreK8sProtectionSetSnapshot(
        input: {
            id: $id,
            jobConfig: $jobConfig
        }
    ) {
        status
        startTime
        progress
        nodeId
        links {
            rel
            href
        }
        id
        error {
            message
        }
        endTime
    }
}`

// updateK8sCluster GraphQL query
var updateK8sClusterQuery = `mutation SdkGolangUpdateK8sCluster($id: UUID!, $config: K8sClusterUpdateInput!) {
    result: updateK8sCluster(input: {id: $id, config: $config}) {
        success
    }
}`

// updateK8sProtectionSet GraphQL query
var updateK8sProtectionSetQuery = `mutation SdkGolangUpdateK8sProtectionSet($id: UUID!, $updateConfig: K8sProtectionSetUpdateInput!) {
    result: updateK8sProtectionSet(input: {id: $id, updateConfig: $updateConfig}) {
        success
    }
}`
